### ISSUE TITLE
parallel map not parallel

### ISSUE THREAD

**Issue by russel** [nikomatsakis/rayon#101]
I think I am just missing something in my haste to get something very small working…

From what I can tell:
```rust
thing.par_iter().map(…).sum()
```
does not do anything in parallel, it computes the maps sequentially.

**Comment by cuviper** [comment]
Rayon knows *how* to split the collection, but it's still an open question to decide *when* to split.  See #81 and [this discussion](https://users.rust-lang.org/t/calling-rayon-users-opinions-wanted/7290) on the users forum.

Try adding a [`weight`](https://docs.rs/rayon/0.4.2/rayon/par_iter/trait.ParallelIterator.html#method.weight) call to tune this, or force the finest granularity with `weight_max`.

**Comment by russel** [comment]
@cuviper Hummm… I was assuming Java/Stream/ForkJoin type thing. Do you have an example of idiomatic use rather than the reference to the API documentation?

**Comment by lilianmoraru** [comment]
@russel Examples of [`weight` usage](https://github.com/nikomatsakis/rayon/blob/ba3e155d72c4fc3a1e5de2b22a527c8ceed70e58/benches/pythagoras.rs#L27-L28) and of [`weight_max` usage](https://github.com/nikomatsakis/rayon/blob/ba3e155d72c4fc3a1e5de2b22a527c8ceed70e58/benches/factorial.rs#L40) can be found in the benchmarks and also in the demos[[1](https://github.com/nikomatsakis/rayon/blob/41230545bd52fde9f207441bd738af1f78d0e09c/demo/nbody/src/nbody.rs#L95), [2](https://github.com/nikomatsakis/rayon/blob/ba3e155d72c4fc3a1e5de2b22a527c8ceed70e58/demo/sieve/src/main.rs#L85)].

**Comment by russel** [comment]
@lilianmoraru  Thanks for those pointers. Those codes have shown me some things about other crates as well as about Rayon. :-)

**Comment by russel** [comment]
```rust
.weight_max()
```
does the job as needed.

To avoid violations of the Principal of Least Surprise I wonder if this "maximal parallelism" is a better default that the "keep it sequential" currently in place> After all the name of the function is `par_iter`.

**Comment by cuviper** [comment]
FWIW, the current default is not "keep it sequential."  Rather, the current default weight is 1.0, and the internal threshold for splitting is 10240.0.  So if your total collection is smaller than that, then yes it will run fully sequentially.  That threshold is rather arbitrary, which is why we're talking about ways to improve the default experience.  I don't think "maximal parallelism" will be the right answer either, but if you want to join the conversation, please visit the links I gave earlier.
