### ISSUE TITLE
into_par_iter not defined for u64

### ISSUE THREAD

**Issue by russel** [nikomatsakis/rayon#102]
I find that:

``` rust
(0..n).into_par_iter…
```

fails if `n` is `u64`, but if I do:

``` rust
(0..n as u32).into_par_iter…
```

everything works fine. Well mostly, but that is a different issue.

**Comment by cuviper** [comment]
That's because a `Range<u64>` is not an `ExactSizeIterator`, since its total length might not fit in a `usize`.  That concept from serial iterators also applies to rayon, since its lengths are also `usize`.

**Comment by russel** [comment]
This is sad since it leads to ugly `as u32` and `as u64` scattered around the place, and problems if you want say 10^30 items. However it sounds like this is a hard constraint and so not fixable. If so then this issue clearly has to be closed.

**Comment by cuviper** [comment]
10^30 items?!?!  At 1ns per item, I figure that will take about 32 *trillion* years of cpu time.  You must have massive parallelization plans... :wink:

It's more realistically annoying to be limited by u32::MAX on 32-bit platforms, this is true, and also annoying that 32-bit concerns are still limiting cases that 64-bit machines could handle just fine.  Rayon is consistent with similar decisions in the standard library, for better or worse.

**Comment by russel** [comment]
10^30 was an over-estimate. :-) Though if we want to do calculations for all the proton in the universe then that is 10^80 – at a rough guess.

For these sorts of computations, Rust has to compete with Chapel (and X10). The computers that excel at these things have many thousands of processors, and cost many millions of pounds.

It seems though the Rust standard library is dictating and they have made a very 32-bit decision in a clearly 64-bit world. :-( I will close this issue, but with a small tear.

**Comment by cuviper** [comment]
If you only care about running on 64-bit, at least you can cast your u64 to/from usize without loss.

**Comment by russel** [comment]
I think for production code I would use usize, and thus avoid the problem. But for some trivial language comparison codes, I have to guarantee 64-bit so that comparisons are not muddied by the 32-bit/64-bit integer and float numbers.

**Comment by nikomatsakis** [comment]
I think it's not out of the question to address this shortcoming. Not that I have a great idea how to do it.

**Comment by nikomatsakis** [comment]
But I'm going to re-open this in any case.

**Comment by Binero** [comment]
Could you add a switch so it works on 64 bit systems?

**Comment by cuviper** [comment]
See #144, which implements these as unindexed producers.

**Comment by nikomatsakis** [comment]
Closed by #144.
