### ISSUE TITLE
merge-sort may have some sort of bug

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#105]
While preparing #104, I tried to convert the mergesort to create the array data using `XorShiftRng`, like `quicksort` -- but it started to fail its correctness assertions! Didn't take the time to look into it deeply though.

cc @edre

**Comment by edre** [comment]
mergesort's correctness check assumes there are no duplicate values (and its original rng ensures this). You can just replace the two >= with > in is_sorted.

**Comment by nikomatsakis** [comment]
@edre ah, very good =) obviously I didn't get into it too deeply.

**Comment by Eh2406** [comment]
move to close?

**Comment by nikomatsakis** [comment]
Yeah, fixed now. =)
