### ISSUE TITLE
deprecate existing weight APIs

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#111]
Per [this comment](https://github.com/nikomatsakis/rayon/pull/106#issuecomment-254469425), we should deprecate the existing weight APIs. I think we probably still want some room for manual tuning, but it should be simpler by default -- and if we are going to let people give fine-grained numbers, it should be tied to the length (like seq. cutoff) rather than some abstract notion of weight. Ideally though we'd add these APIs **along with representative benchmarks** where they are needed.

**Comment by Eh2406** [comment]
As a quick test I took a work project and cargo updated to 0.4.3. With `weight_max` it runes 32s. Then I removed the `weight_max` and it runs in 48s. (each best of 3 runs, wall clock time.) Did I test this correctly? Is there any info I can get so as to be helpful?  Unfortunately I can't share the example.  :-(

**Comment by cuviper** [comment]
@Eh2406 can you characterize the workload somehow?  Is the work well balanced for each item, or skewed heavily?  Maybe you can synthesize something that performs similarly?

For possible tunables related to length, I think we'll want both a minimum (don't bother splitting below this length) and a maximum (always split at least down to this length), where `weight_max()` corresponds to asking for a maximum length 1.

**Comment by Eh2406** [comment]
so I am running on a `intel core i5-5200u @ 2.2GHz 2.19 GHz`
I Isolated the first stage, the stages are run sequentially but each one calls into_par_iter.
The first stage, actually looks good.
with `weight_max` 61s, 56s, 51s
without 46s, 58s, 59s
So let me try to isolate the second stage, as so far the new algorithm seems comparable.

**Comment by fkjogu** [comment]
I really dislike the `weights` mechanism, since it relies on an arbitrary threshold. Which makes it meaningless as a measure, since the expensiveness of task can also vary arbitrarily. So I'm in favor removing it.

However, I'd like to retain some control, how the work is split. So I'd propose to simply introduce an optional way, to specify the number of threads used.

Something like `.par_iter().jobs(42).whatever()`.

It is minimally intrusive, but offers precise manual control, if needed.

**Comment by nikomatsakis** [comment]
I think @cuviper has some thoughts here and wanted to take a crack at this. I'm going to assign to them and remove the Help-Wanted label for now.
