### ISSUE TITLE
change name of `threadpool::install`?

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#119]
Currently, the question is, do we want a different name than `threadpool::install()`? Something that makes it clearer that we will execute the closure *in* the thread-pool?

--- 

**Original post:**

Currently, `threadpool::install` injects its closure argument in one of the worker threads for the threadpool. Since we are then executing in the worker threads, calls to `join` or `scope::spawn` naturally execute in that threadpool. I chose this design because it's zero overhead -- the logic for `join` and `scope::spawn` are the same ("if in worker thread, push, else inject into global pool").

However, I have been contemplating a change where we instead set a thread-local variable to point at the thread-pool, and then consult this thread-local variable when injecting threads. The reason is that I want people to be able to `install` at a very high point in their callstack without disturbing thread-local data they may need to use before they spawn tasks (once they spawn, there is not much I can do about _that_ of course).

**Comment by nikomatsakis** [comment]
After some discussion with @cuviper, we decided that this mechanism as it is is useful. The only thing we might want to do before 1.0 is to deprecate and rename it to something more clear.

**Comment by cuviper** [comment]
If we wanted to rename, we missed that chance by releasing rayon-core 1.0.  I don't think we should use deprecation now unless there's a very strong reason why the current name is bad.  But I think the documentation is clear enough about what this does: "Executes `op` within the threadpool."  So... close?

**Comment by nikomatsakis** [comment]
Yes.
