### ISSUE TITLE
Error when trying to install rayon 0.4.3

### ISSUE THREAD

**Issue by durango** [nikomatsakis/rayon#125]
```
→ rustc -V
rustc 1.9.0 (e4e8b6668 2016-05-18)
→ cargo -V
cargo 0.10.0-nightly (10ddd7d 2016-04-08)
```

Compiling rayon v0.4.3
  Running `rustc /Users/daniel/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.4.3/src/lib.rs --crate-name rayon --crate-type lib -g -C metadata=5441ea551292b9c3 -C extra-filename=-5441ea551292b9c3 --out-dir /Users/daniel/game/target/debug/deps --emit=dep-info,link -L dependency=/Users/daniel/game/target/debug/deps -L dependency=/Users/daniel/game/target/debug/deps --extern rand=/Users/daniel/game/target/debug/deps/librand-c724acb3942597d1.rlib --extern num_cpus=/Users/daniel/game/target/debug/deps/libnum_cpus-0d0496d141db0602.rlib --extern libc=/Users/daniel/game/target/debug/deps/liblibc-56a988296c48c60c.rlib --extern deque=/Users/daniel/game/target/debug/deps/libdeque-9a8e24ef39a44da6.rlib --cap-lints allow`
    Fresh flate2 v0.2.14
    Fresh core-foundation-sys v0.2.2
    Fresh cgl v0.1.5
    Fresh png v0.5.2
    Fresh core-foundation v0.2.2
    Fresh time v0.1.35
    Fresh piston-float v0.2.0
    Fresh core-graphics v0.3.2
    Fresh vecmath v0.2.0
    Fresh piston-viewport v0.2.0
    Fresh cocoa v0.3.3
    Fresh pistoncore-input v0.14.0
    Fresh piston2d-graphics v0.18.0
    Fresh glutin v0.6.2
    Fresh pistoncore-window v0.23.0
    Fresh pistoncore-event_loop v0.26.0
    Fresh pistoncore-glutin_window v0.31.0
    Fresh piston v0.26.0
/Users/daniel/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.4.3/src/par_iter/internal.rs:96:47: 96:48 error: no rules expected the token `;`
/Users/daniel/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.4.3/src/par_iter/internal.rs:96         thread_local!{ static ID: bool = false; }
                                                                                                                                                 ^
error: Could not compile `rayon`.

Caused by:
Process didn't exit successfully: `rustc /Users/daniel/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.4.3/src/lib.rs --crate-name rayon --crate-type lib -g -C metadata=5441ea551292b9c3 -C extra-filename=-5441ea551292b9c3 --out-dir /Users/daniel/game/target/debug/deps --emit=dep-info,link -L dependency=/Users/daniel/game/target/debug/deps -L dependency=/Users/daniel/game/target/debug/deps --extern rand=/Users/daniel/game/target/debug/deps/librand-c724acb3942597d1.rlib --extern num_cpus=/Users/daniel/game/target/debug/deps/libnum_cpus-0d0496d141db0602.rlib --extern libc=/Users/daniel/game/target/debug/deps/liblibc-56a988296c48c60c.rlib --extern deque=/Users/daniel/game/target/debug/deps/libdeque-9a8e24ef39a44da6.rlib --cap-lints allow` (exit code: 101)

```

https://github.com/nikomatsakis/rayon/blob/c91ea503ba0dee8dd1cf3575e8a4adf86e2d33d8/src/par_iter/internal.rs#L96

Any ideas? (Mac OSX)
```

**Comment by Eh2406** [comment]
the discussion continues in https://github.com/nikomatsakis/rayon/pull/126

**Comment by nikomatsakis** [comment]
So this should be fixed now, but we still need a new release I suppose.

**Comment by cuviper** [comment]
I think we're done here.  Note we're up to 1.12.0 minimum now. (#171)
