### ISSUE TITLE
No way to force par_iter to run in parallel and not fall back to sequential execution

### ISSUE THREAD

**Issue by kaksmet** [nikomatsakis/rayon#13]
Currently there is no way to force par_iter to run in parallel and not fall back to sequential execution (except setting weight to an arbitrarily high value).

I think a simple method that guarantees the par_iter will run in parallel would suffice.

**Comment by nikomatsakis** [comment]
> Currently there is no way to force par_iter to run in parallel and not fall back to sequential execution (except setting weight to an arbitrarily high value).

What is wrong with that? I imagined something like `weight(f64::INFINITY)`.
