### ISSUE TITLE
Feature Request: ability to name Rayon threads

### ISSUE THREAD

**Issue by jwilm** [nikomatsakis/rayon#142]
Currently the thread pool used by Rayon inherits their names from the process title. We like to track CPU utilization by thread in our application; it would be nice if Rayon added a configuration parameter to name the threads.

I'd be willing to make a PR if the feature would be accepted, but I wanted to check that's the case first.

Thanks!

**Comment by nikomatsakis** [comment]
@jwilm seems like a reasonable feature, sure!

I imagine it would be done by modifying the `Configuration` to include a "base name" for the Rayon threads or something like that, and then modifying the `Registry::new()` function (in `src/thread_pool.rs`) to give the threads names.

**Comment by martinhath** [comment]
I suppose this can be closed, as #202 is merged 😄

**Comment by jwilm** [comment]
Done! Thanks for implementing it :D
