### ISSUE TITLE
Error compiling Rayon 0.5.0

### ISSUE THREAD

**Issue by aaronhyperum** [nikomatsakis/rayon#145]
```
/Users/Home/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.5.0/src/scope/test.rs:88:34: 88:38 error: expected identifier, found keyword `impl`
/Users/Home/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.5.0/src/scope/test.rs:88     pub fn iter<'s>(&'s self) -> impl Iterator<Item=&'s T> + 's
                                                                                                                              ^~~~
/Users/Home/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.5.0/src/scope/test.rs:88:39: 88:47 error: expected one of `!`, `(`, `::`, `<`, `where`, or `{`, found `Iterator`
/Users/Home/.cargo/registry/src/github.com-88ac128001ac3a9a/rayon-0.5.0/src/scope/test.rs:88     pub fn iter<'s>(&'s self) -> impl Iterator<Item=&'s T> + 's
```

**Comment by cuviper** [comment]
Rayon requires Rust nightly for testing, but ideally that wouldn't matter for normal builds.  Unfortunately, modules like this are still parsed, even though it's gated by `#[cfg(test)]`, and that `impl Trait` syntax wasn't understood until Rust 1.12.

One way to dodge this is to move such tests into standalone binaries in the `tests/` directory.  This only works if the tests don't need internal access - if they only use the public API.

**Comment by nikomatsakis** [comment]
In this case, I think that the tests only exercise the public API; therefore we *could* move the to the `pos-tests-run` directory. We discussed before trying to set some sort of "minimum supported version" for Rayon. I'm kind of "mid-way" on this: in the absence of LTO or some other such thing, I'm mostly of the opinion that Rust users ought to stay up on the most recent version of stable (after all, we don't port backfixes and so forth, and even if we do, we only do it to the most recent version of stable). However, it seems ok to support older Rust versions if it's easy to do so.

@aaronhyperum by the way, presuming you use `rustup`, you can always do `rustup upgrade stable` to get the latest release, which would fix this problem.

**Comment by aaronhyperum** [comment]
Ah, that makes sense. I updated rustc and it compiled fine.

**Comment by cuviper** [comment]
> We discussed before trying to set some sort of "minimum supported version" for Rayon. I'm kind of "mid-way" on this: in the absence of LTO or some other such thing, I'm mostly of the opinion that Rust users ought to stay up on the most recent version of stable (after all, we don't port backfixes and so forth, and even if we do, we only do it to the most recent version of stable). However, it seems ok to support older Rust versions if it's easy to do so.

You mean LTS?  But even if rust-lang.org rarely backports anything, an enterprise distro might apply fixes to their packages.  I think we should at least spell out what version we know works, and test that explicitly in travis.  The longer we can maintain older support, the better, but that's a judgement call if there comes some new Rust feature that would really help Rayon.
