### ISSUE TITLE
`max`, `min`, `max_by_key`, `min_by_key` should match sequential iterators

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#148]
The parallel `max` and `min` have a different signature from the sequential variant. They return `Self::Item` instead of `Option<Self::Item>`. They also don't work on all `Ord` types. (These are related.) It'd be good to change them to match, I think. In so doing, we can also add support for `max_by_key` and `min_by_key`. This would also simplify the implementation to boot!

The idea is to replace the [existing, oddball methods](https://github.com/nikomatsakis/rayon/blob/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/mod.rs#L350-L354) with methods [that invoke `reduce_with()`](https://github.com/nikomatsakis/rayon/blob/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/mod.rs#L217-L221). They should work for any iterator where `Self::Item: Ord`.

If you've not hacked on Rayon before, also check out the [guide to development](https://github.com/nikomatsakis/rayon/wiki/Guide-to-Development).

**Comment by utkarshkukreti** [comment]
I'm working on this.

**Comment by tapeinosyne** [comment]
Sorry about the unfortunate interference; I wrote the patch this morning, but only now noticed @utkarshkukreti's message.

**Comment by utkarshkukreti** [comment]
No problem @tapeinosyne. I'll work on something else :)
