### ISSUE TITLE
rename `mul` to `product`

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#149]
To match sequential iterators, the parallel iterator `mul()` method should be renamed to `product()`.

If you've not hacked on Rayon before, also check out the [guide to development](https://github.com/nikomatsakis/rayon/wiki/Guide-to-Development).

**Comment by PlasmaPower** [comment]
Can this issue be closed?

**Comment by nikomatsakis** [comment]
Indeed!
