### ISSUE TITLE
support `rev` on indexed producers

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#150]
We should support the standard `rev()` combinator from sequential iterators. I am only envisioning supporting it for *indexed* parallel iterators. 

I think to do this we'd have to extend the `Producer` trait so that it can (at least sometimes? maybe always?) support a `rev()` method. I'm not 100% sure.

The basic steps though would be as follows:

- We would be modeling this change roughly on the [existing `Enumerate` combinator](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L6-L8); so we'll add a type like `Rev<M>`
- Like `Enumerate`, `Rev<M>` will implement the various parallel iterators traits, but [only if `M: IndexedParallelIterator`](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L16-L17)
- By far the most complex part is implementing [the `with_producer()` method](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L51-L72). As [described in the parallel iterator README](https://github.com/nikomatsakis/rayon/blob/master/src/par_iter/README.md#what-on-earth-is-producercallback), this method is basically a callback scheme:
    - The heart of it is that you [ask your base producer (the one that we are going to be skipping over) to call you back with a producer](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0//src/par_iter/enumerate.rs#L54).
    - But it can't use Rust's closures, so you have to [make a custom struct](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L56-L58) which [implements the `ProducerCallback` trait](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L60-L62).
    - Ultimately, [the `callback()` method of this struct will be invoked](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L67-L69) with the base producer.
    - At this point, `Enumerate` [wraps that producer it was given in its own producer](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L67-L68) and then [invokes the callback with the wrapper producer](https://github.com/nikomatsakis/rayon/tree/feacfc2d7baebb2df0c9a99699952db7d51185c0/src/par_iter/enumerate.rs#L69). I am not quite sure what `Rev` would do.

So this last point is where things get interesting. I suspect that `Rev` will actually wind up invoking `producer.reverse()` to reverse the producer it was given and pass that along. Since all producers support indexing at arbitrary points, probably they can all support reversing too; but we'll have to implement that method down the line, for all the producer impls (which aren't *that* many).

I'd rather this task "moderate" -- the complexity level is low, but it's some grunt work, and of course if you're not familiar with the system, that'll take a bit of getting used to.

If you've not hacked on Rayon before, also check out the [guide to development](https://github.com/nikomatsakis/rayon/wiki/Guide-to-Development).

**Comment by jonathandturner** [comment]
Taking a look at this one...

**Comment by jonathandturner** [comment]
In case other people want to poke on what I have so far: https://github.com/jonathandturner/rayon/tree/rev

It compiles but doesn't yet work.  You can see some of the areas that need to be fixed looking for FIXME.

The three places that I wasn't quite sure how to handle: 

* Ranges: We should be able to pass around some form of reversed ranges, but I haven't yet come up with the right approach
* split_at: Do we want to split from the back of an producer rather than from the front in a reversed producer?
* vec: Vec has some added trickiness that does a bit more than Slice.  I haven't quite figured out how to model it, yet.

**Comment by nikomatsakis** [comment]
So I did some investigation here. I wanted to explore an alternate route to what @jonathandturner was pursuing: instead of having each `Producer` able to convert themselves into a reverse producer, I wanted to see if we could instead say that each producer yields a `DoubleEndedIterator`. Then we could have a single `RevProducer<P>` producer that converts any other producer P into its reverse: it would just adjust the `split_at` index, and `into_iter()` would do `self.base.into_iter().rev()`.

It turns out that this **mostly** works, but I ran into a few hitches:

- It turns out that you need to guarantee that the iterators support `ExactSizeIterator` too, because `zip` only implements `DoubleEndedIterator` if its parts implement `ExactSizeIterator`.
- Unfortunately, `std::iter::Chain` and `std::iter::SliceDrain` do not implement `ExactSizeIterator` 
    - I think there is no good reason for this in either case, just an oversight
    - We can fix this by making our own version of chain locally, and submitting a patch to libstd
- Also, `RangeFrom` does not implement `DoubleEndedIterator`, and it is used by `enumerate()`
    - we can replace `0..` with `0..usize::MAX`, but that's not *quite* right if you happen to produce `usize::MAX` items
    - we can also just write our own iterator here too :)

So, this other approach seems kind of annoying, but also promising. Probably easier overall.

I did run into *other* problem. I wanted to write the following:

```rust
pub trait Producer: IntoIterator + Send + Sized
    where Self::IntoIter: DoubleEndedIterator + ExactSizeIterator
```

as a way to say "the iterator produced by `IntoIter` must additionally meet these bounds. But in doing so I encountered various inexplicable errors that I believe to be compiler bugs. So if we took my approach we'd also have to inline the `IntoIterator` methods into `Producer`, something like this:

```rust
pub trait Producer: Send + Sized {
    type Item;
    type IntoIter: Iterator<Item = Self::Item> + DoubleEndedIterator + ExactSizeIterator;
    fn into_iter(self) -> Self::IntoIter;
}
```

Not really a big deal.

**Comment by nikomatsakis** [comment]
(Perhaps not surprisingly, it seems like many of the difficulties I encountered are in the same general area as the problems that @jonathandturner encountered; various shortcomings of the stdlib.)

**Comment by nikomatsakis** [comment]
This is [the branch where I did my experiments](https://github.com/nikomatsakis/rayon/commit/8f64889a2966dee53ca7bd3e78b5a525809ed70e). Note that I just added a new member (`DoubleEndedIterator`) to `Producer`, just to see what problems I would encounter. That is, I wouldn't really start the actual code from this branch.

**Comment by nikomatsakis** [comment]
Oh darn it I remember now why `Chain` does not implement `ExactSizeIterator` -- because of the possibility of overflow. That ... is so annoying.

**Comment by nikomatsakis** [comment]
I don't think there is a good reason for the drain family to not be exact, though?

**Comment by cuviper** [comment]
You said `std::iter::SliceDrain` before, which doesn't exist, but `std::vec::Drain` *is* exact and double-ended.  Were you thinking of `rayon::par_iter::vec::SliceDrain`?  That certainly can be exact and double-ended too, as it's just a wrapper on `std::slice::IterMut` -- we just haven't needed it to have additional traits yet.

**Comment by nikomatsakis** [comment]
Yes I think that's all correct

**Comment by schuster** [comment]
I've been looking into this a bit and wrapping my head around the issues. Is there any concern that requiring *all* producers to yield double-ended, exact-size iterators is too strong a constraint? The current set of producers seems okay so far (although `Chain` is an example that doesn't fit quite so neatly), and I haven't come up with a hypothetical problematic producer yet, but my gut says maybe this could cause issues in the future. Is that a valid concern? 

A third possible approach: support `Rev` only for iterators that can implement a new `DoubleEndedParallelIterator` trait that includes a `with_double_ended_producer` callback function. A bit redundant, but without associated an `Producer` type on `IndexedParallelIterator` (which I understand from the blog post a while back causes its own problems), the redundancy seems unavoidable if we don't want to apply this constraint to all producers.

**Comment by schuster** [comment]
I think I answered my own question. The only iterators that can be used in producer mode are `IndexedParallelIterator`s, which requires `ExactParallelIterator`. If the parallel iterator has both of those capabilities, then *presumably* the underlying serial `Iterator` does, too. If we know the length of an iterator and can index into it, then there's a way to treat it as a `DoubleEndedIterator`. So, in theory, every producer should yield an iterator that is both `ExactSizeIterator` and `DoubleEndedIterator`.

The only problem is that in practice some things don't actually implement those traits even though they could. I think that's just a matter of fixing up the standard implementations, as needed, and deciding on weird cases like whether `Chain` really should be `ExactParallelIterator`, even though there's a possibility of overflow. Those all seem orthogonal to the overall approach of requiring these traits on producers, though, so I'm going to give that a shot.

I may have just said what everyone else here already realized, but writing it out at least helped me understand the full issue.

**Comment by nikomatsakis** [comment]
@schuster that all sounds correct, yes.

**Comment by schuster** [comment]
I've just about got this working using @nikomatsakis 's approach. The only remaining question is what to do about `Chain`'s overflow issue. I could imagine two different implementations of `Chain`:

1. An "unsafe" version that implements `ExactParallelIterator` and relies on the user to never create it with base iterators that might cause it to overflow. This is basically what exists now, except we'd have to reimplement the sequential iterator to apply `ExactParallelIterator`.
2. A "safe" version that does some kind of wrapping addition to avoid overflow, similar to what `RangeIter` does for 64-bit elements (although I haven't thought through the math yet). This wouldn't implement `ExactParallelIterator`, but it would guarantee never to overflow.

Is there a preference between these two? Would it perhaps make sense to have both?

**Comment by cuviper** [comment]
> except we'd have to reimplement the sequential iterator to apply ExactParallelIterator.

Why is the sequential iterator a problem?  Why does it need `ExactSizeIterator` and not just `DoubleEndedIterator`?  (I'm probably just forgetting something...)

**Comment by schuster** [comment]
As @nikomatsakis mentioned above, `zip` only implements `DoubleEndedIterator` if the iterators it's zipping together implement `ExactSizeIterator`. That's because when zip reverses itself, it needs to determine which index is the new "start" index in the longer part, which it does by getting the length of the shorter part.

**Comment by cuviper** [comment]
Ah, yes, `zip`.  Hmm.

Note that re-implementing the sequential `Chain` doesn't have to be clever at all.  It could just be a pass-through wrapper on `std::iter::Chain` with `ExactSizeIterator` thrown on top.

I'm not sure what your second "safe" version is proposing.  The 64-bit `RangeIter` wrapping has more to do with edge cases of signed ranges for `i64` in particular -- there's a better comment about this in its non-64-bit `Producer`.  But for chain, I'd expect we're already fine in the non-exact mode, as its `drive` and `drive_unindexed` just hand off to the underlying iterators in turn.

**Comment by cuviper** [comment]
cc @bluss - would you have any trouble with requiring `DoubleEndedIterator` and `ExactSizeIterator` from your `ndarray` `Producer`?

**Comment by bluss** [comment]
That would be fine. The one that's using Producer is already indexed, ESI and the base iterator is DEI too. The other par iter implementation is UnindexedProducer, and it can't be DEI. Once it's indexed it's simple.

**Comment by bluss** [comment]
When it comes to libstd `.zip()` I don't like that it is double ended, it's not worth the complexity. At least not double ended with the current bounds.

Consider single threaded `(0..5).map(f).zip((0..3).map(g))`. The iterator has length 3. How many times are `f` and `g` called during the iteration?

The answer is f four, and g three.

I've never thought about that before, but the reverse case is not at all consistent with the forward behaviour when it comes to side effects.

(The f four, g three behaviour was painstakingly preserved through the zip specialization, so that the specialization was identical in side effects. That said, I haven't considered the exact DEI side effects before now.)

I don't know what your rayon variant of this is, but basing zip on indexed iterators avoids a lot of the problem, so you probably don't have it.

**Comment by nikomatsakis** [comment]
> I don't know what your rayon variant of this is, but basing zip on indexed iterators avoids a lot of the problem, so you probably don't have it.

I thought about this some time back and decided that this is the case.

**Comment by cuviper** [comment]
> I did run into other problem. I wanted to write the following:
> 
> ```rust
> pub trait Producer: IntoIterator + Send + Sized
>     where Self::IntoIter: DoubleEndedIterator + ExactSizeIterator
> ```
> 
> as a way to say "the iterator produced by IntoIter must additionally meet these bounds. But in doing so I encountered various inexplicable errors that I believe to be compiler bugs.

Ah, I just commented about this on #224.  I believe that compiler bug is rust-lang/rust#20671.
