### ISSUE TITLE
A simpler driver that uses split in half (not indexable)

### ISSUE THREAD

**Issue by bluss** [nikomatsakis/rayon#180]
This is something ndarray could make use of.

We have a 2d array (a matrix) of m rows and n columns. Its array view, just like its element iterator has m × n items.

I would like to have its array view be a parallel iterator. We can't split it at arbitrary element ordinal, but we can split it according to the [split at method](https://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.split_at); along an axis, at an index.

What would work well for the array view is simply a more basic producer trait that requires the ability to split the producer in half, and each part should be able to tell how many elements it contains.

The ArrayView will spit itself along the axis with the largest stride (not along the longest axis). This split ensures that elements processed in one job are close to each other in memory.

In current ndarray that's implemented as:

```rust
let axis = view.max_stride_axis();
let mid = view.len_of(axis);
view.split_at(axis, mid)
```

I can implement this kind of split/join logic manually using the public parts of rayon (in the internal module), but it requires recreating `Splitter` and the weights logic from scratch.

For illustration, something like this:

```rust
fn drive_split_producer<Sp, C>(producer: Sp, consumer: C) -> C::Result
    where Sp: SplitProducer,
          C: UnindexedConsumer<Sp::Item>,
{
    if consumer.full() {
        consumer.into_folder().complete()
    } else {
        if producer.cost() > 1024. { // FIXME
            let (left_producer, right_producer) = producer.split_in_half();
            let mid = left_producer.len();
            let (left_consumer, right_consumer, reducer) = consumer.split_at(mid);
            let (left_result, right_result) =
                join(move || drive_split_producer(left_producer, left_consumer),
                     move || drive_split_producer(right_producer, right_consumer));
            reducer.reduce(left_result, right_result)
        } else {
            let mut folder = consumer.into_folder();
            producer.into_iter().fold(folder, <_>::consume).complete()
        }
    }
}

pub trait SplitProducer : IntoIterator + Send + Sync + Sized {
    fn len(&self) -> usize;
    fn split_in_half(self) -> (Self, Self);
    fn cost(&self) -> f64 { self.len() as f64 }
}
```

**Comment by cuviper** [comment]
Did you see the `UnindexedProducer`?  e.g. used by `RangeIter<u64>` and `ParChars`.

**Comment by bluss** [comment]
No, I'm working with rayon from crates.io, that's probably it?

**Comment by cuviper** [comment]
Yeah, both of those were added after 0.5.0.  We're probably due for another release...

**Comment by cuviper** [comment]
But also, since they're not released yet, it's a good time for you to see if `UnindexedProducer` meets your needs too, so we could tweak it before it's really out there.

**Comment by bluss** [comment]
Great, I'll try. I added rayon git to my deps but the reason I chose 0.5 was: racer only autocompletes and go to definition for crates.io deps (for some reason). And the latter is invaluable..

**Comment by cuviper** [comment]
Perhaps your par-iter should split by just rows, and then separately you could flat-map a par-iter on the row's elements?  Or by columns first, which ever is better for data locality.  You could expose the intermediate iterator, or hide these steps internally, up to you.  But I think you could keep things indexible this way.

**Comment by bluss** [comment]
for ndarray this needs to be n-ary (2d is the simple case) and data locality depends on the array value (it's not type level information).

ndarray already has an axis iterator that is indexable (`AxisIter`). That's the simple case (shown in the other issue) and it's already done. Now we're attacking (`Iter`).

**Comment by cuviper** [comment]
Alright, makes sense.

**Comment by bluss** [comment]
Thanks for the help so far, the new UnindexedProducer fits this use case precisely. So implementing even this wasn't hard, once the boilerplate was mastered.

Since ndarray deals with varying memory layouts, it does benefit from being able to select which and tune the inner loops of operations (so it encourages `map` instead of a for loop and so on). For that reason too, the individual elements iterator is maybe not a good idea for its rayon integration. Ndarray would like to control and implement the inner loop too (the one that applies the folder). It's along the same ideas as [link](https://medium.com/@veedrac/rust-is-slow-and-i-am-the-cure-32facc0fdcb), which can for example be addressed by using `.fold()` instead of `for` as the innermost loop.

**Comment by bluss** [comment]
I was going to say, Implementation turned out to be easy :+1: , but now it's ensuring performance that is going to take time.

**Comment by bluss** [comment]
This seems to be fixed in git! See UnindexedProducer.

**Comment by cuviper** [comment]
I'm eager to see your expertise applied to Rayon!

**Comment by bluss** [comment]
Hehe that's the right way to pull people in.

**Comment by bluss** [comment]
The proposal for iterators to adapt their inner loops themselves is here https://internals.rust-lang.org/t/pre-rfc-fold-ok-is-composable-internal-iteration/4434

Rayon would then need to use `.fold_ok` (or what it would be called) as the inner loop. Which fits, since the inner loop is a potentially short-circuiting circuiting one.
