### ISSUE TITLE
Split crates between user and implementor APIs

### ISSUE THREAD

**Issue by cuviper** [nikomatsakis/rayon#192]
As discussed in #188, it would be useful to have a clearer separation between interfaces that are stable for users to invoke versus those that are needed for *implementing* parallel traits. We would like to reach Rayon 1.0 fairly soon, but it would be a shame to have to lock down "internal" details too. If we can split that into a separate crate, then it can have its own versioning, with more frequent semver bumps that don't impact "plain" Rayon use. This should also fix #177, as we can document all the gory details that we currently hide from regular users. 

CC @bluss who was pressing for better policy around API boundaries.  And I'm signing myself because I'm interested and I think I have a good feel for how to do this. 😀

**Comment by nikomatsakis** [comment]
I've been wanting for some time to extract out the internal threadpool as well, which is a similar such layer. I think there are some existing issues though. I wanted to land the various refactorings i've been doing first before attempting it, though.

**Comment by bluss** [comment]
I'm not asking for a big policy or anything, just “I can't have ndarray depend on rayon until it's clarified that there exists a versioned interface.” https://github.com/nikomatsakis/rayon/pull/188#issuecomment-269668783

I would not put this in 1.0, but rather attempt the split as soon as possible and see what works, without committing to any particular version up front. I am a bit skeptical that the internals can be split out, since they are tied into implementing rayon traits for standard library types.

**Comment by cuviper** [comment]
I put this on 1.0 because it's something we need to figure out *before* 1.0, not to imply waiting until then.  But we want Rayon 1.0 soonish anyway, in accordance with the 2017 roadmap goal for 1.0 crates.

I've been playing with this a few different ways, and right now I'm leaning towards a `rayon-core` crate with pretty much everything as it is now, but splitting e.g. `ParallelIterator` (the user interface) and `ParallelIteratorImpl` (the implementor's interface).  Then the main `rayon` crate becomes basically just a facade with the hand-picked stable interfaces, which we can promote to 1.0, while `rayon-core` can still iterate with pre-1.0 versions.

**Comment by nikomatsakis** [comment]
@cuviper 

> I've been playing with this a few different ways, and right now I'm leaning towards a rayon-core crate with pretty much everything as it is now

cool, good to know you are looking into this!

**Comment by nikomatsakis** [comment]
I feel this is fixed with https://github.com/nikomatsakis/rayon/pull/227
