### ISSUE TITLE
make `Registry::new()` panic-safe 

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#205]
As discussed in #202, `Registry::new()` is not panic-safe. The call to `spawn()` for a worker thread might panic, which would leave the other worker threads hanging around. It'd be good to setup a guard or something to encourage those workers to shut themselves down.

One simple way to do this would be to have one-shot channel per thread, with `Registry::new()` sending a `()` message once everybody is up and going. That way, if any of the threads panic, the sender of the channel will be dropped and the other threads will receive an error.

**Comment by cuviper** [comment]
The slight irony is that `Builder::spawn()` returns a `Result` instead of panicking, so #202 is actually improving that situation!  (But it doesn't check the result, hmm -- I'll note that.)

Do you see an actual safety issue here?  Or just leaking threads?

**Comment by nikomatsakis** [comment]
@cuviper just leaking threads, I think
