### ISSUE TITLE
Range<usize> does not implement IntoParallelIterator

### ISSUE THREAD

**Issue by yongqli** [nikomatsakis/rayon#223]
This code fails to compile:

    extern crate rayon;

    use rayon::prelude::*;

    pub fn test() -> Vec<usize> {
        (0..10usize).par_iter().map(|i| i).collect()
    }

with:

    error: no method named `par_iter` found for type `std::ops::Range<usize>` in the current scope
     --> src/lib.rs:6:18
      |
    6 |     (0..10usize).par_iter().map(|i| i).collect()
      |                  ^^^^^^^^
      |
      = note: the method `par_iter` exists but the following trait bounds were not satisfied: `&std::ops::Range<usize> : rayon::par_iter::IntoParallelIterator`

How can I fix this?

**Comment by cuviper** [comment]
You want `into_par_iter()`, whereas `par_iter()` is for iterating collections by reference.

**Comment by yongqli** [comment]
Thanks!
