### ISSUE TITLE
injecting code into rayon's thread startup and shutdown

### ISSUE THREAD

**Issue by froydnj** [nikomatsakis/rayon#225]
**EDIT:** This is tagged as **help wanted**. There is some [advice for how to implement this in a comment below](https://github.com/nikomatsakis/rayon/issues/225#issuecomment-284222108).

---

I'm opening this issue because I'd like to explore the feasibility of being able to run code when a rayon thread starts and before it exits.

Background: We're using a Rayon thread pool to do parallel styling in the [Stylo](https://wiki.mozilla.org/Quantum/Stylo) project.  As part of that work, we'd like to make Rayon threads profilable via the [Gecko profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) so that work happening in the thread pool is visible to the profiler.  The profiler, for better or worse, will only profile threads that are explicitly registered with the profiler.

So, to make all of this come together, the threads Rayon creates [need to be registered with the profiler](https://bugzilla.mozilla.org/show_bug.cgi?id=1322656).  And the best way that I can see of doing that is to have some sort of mechanism inside Rayon the provides a place where you can run code at thread startup or thread shutdown.  (You could register threads on-demand from the parallel styler, I think, but that would run into [issues with potential thread-id re-use](https://docs.rs/rayon/0.6.0/rayon/struct.ThreadPool.html#future-compatibility-note), and would add an undesirable amount of overhead to the styler.)

Is this a feasible thing to add?

cc @mstange @bholley

**Comment by bholley** [comment]
The simplest thing would probably be an API to run a function exactly once on each thread in the pool. But I suppose that might become problematic if the thread pool ever changes size dynamically.

I'll defer to @nikomatsakis on what he prefers here.

**Comment by mstange** [comment]
We might not need this if https://bugzilla.mozilla.org/show_bug.cgi?id=1341811 works out. But I don't know how feasible that one is.

**Comment by nikomatsakis** [comment]
I don't have a problem with having a fn that runs on thread startup -- would you also want one that runs on thread teardown?

**Comment by nikomatsakis** [comment]
I'm marking this as "help-wanted", as it seems like a relatively straightforward change. I think the basic gist of what I would do:

- add a method to [the `Configuration` type](https://github.com/nikomatsakis/rayon/blob/master/rayon-core/src/configuration.rs#L48) that stores a "execute on thread-start" closure, probably looking something [like `set_panic_handler`](https://github.com/nikomatsakis/rayon/blob/master/rayon-core/src/configuration.rs#L123)
- add code to the [worker main loop](https://github.com/nikomatsakis/rayon/blob/master/rayon-core/src/registry.rs#L485) to invoke this closure
    - we should invoke it using [`unwind::halt_unwinding`](https://github.com/nikomatsakis/rayon/blob/master/rayon-core/src/unwind.rs#L16) and, if `Err(e)` is returned (i.e., if a panic occurs), invoke [the panic handler from the configuration](https://github.com/nikomatsakis/rayon/blob/master/rayon-core/src/registry.rs#L160) by calling `registry.handle_panic(e)`

**Comment by bholley** [comment]
@froydnj can you confirm whether you need something to run at thread teardown as well?

**Comment by Enamex** [comment]
[**@bholley**](https://github.com/bholley) commented on [Mar 6, 2017, 8:20 PM GMT+2](https://github.com/nikomatsakis/rayon/issues/225#issuecomment-284484114 "2017-03-06T18:20:57Z - Replied by Github Reply Comments"):
> [@froydnj](https://github.com/froydnj) can you confirm whether you need something to run at thread teardown as well?

Is teardown somehow different from exiting? froydnj mentioned wanting to run code at start and at exit.

**Comment by mstange** [comment]
Yes, we'd need to run something both at the start and the end of the thread. These two functions, to be specific: http://searchfox.org/mozilla-central/rev/1bc7720a434af3c13b68b8d69f92078cae8890c4/tools/profiler/public/GeckoProfiler.h#268-271

**Comment by bholley** [comment]
> Is teardown somehow different from exiting? froydnj mentioned wanting to run code at start and at exit.

At thread exit, yes.

**Comment by cpeterso** [comment]
The Stylo team is tracking the Gecko Profiler half of this work in [Firefox bug 1322656](https://bugzilla.mozilla.org/show_bug.cgi?id=1322656).

**Comment by nikomatsakis** [comment]
So now that #271 landed, this is basically done, right? We just need to issue Rayon 0.7.

**Comment by froydnj** [comment]
> So now that #271 landed, this is basically done, right? We just need to issue Rayon 0.7.

That's correct.

**Comment by nikomatsakis** [comment]
Very good!
