### ISSUE TITLE
[docs] the `FlatMap` struct needs documentation

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#241]
The `FlatMap` struct implements the parallel iterator `flat_map()` combinator. It needs some simple docs that say precisely that and link to `flat_map()` method for more information.

**Comment by leshow** [comment]
I'd like to take some of these off your plate if I can. I'm not sure how to do an internal link to some other part of the docs however, if you could drop that bit of knowledge on me I could submit a PR for a bunch of these.

**Comment by leshow** [comment]
I believe I've figured it out looking at the rust src docs. I'll submit a PR in a bit.

**Comment by nikomatsakis** [comment]
Looks like #248 closed this.
