### ISSUE TITLE
change type parameter names to be a single letter

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#249]
I think that the long names for type parameters (like `MAP_OP`) have not proven to be a boon to readability as I had hoped. At this point, I think we should just use single letters (like `M`), with documentation for anything if the role is not clear or needs to be understood by end-users.

I'm going to put this in the 1.0 milestone, but it could be removed since it's not a breaking change to do later. Just a polish thing.

**Comment by leshow** [comment]
I can take some of these, after looking at the code though, I'd like to suggest using `F` instead of `M`, as `M` is already used as a type parameter in a lot of these, for example:

```
pub struct FlatMap<M: ParallelIterator, F> {
    base: M,
    map_op: F,
}
```

**Comment by nikomatsakis** [comment]
@leshow 👍

**Comment by nikomatsakis** [comment]
This is basically done in #261
