### ISSUE TITLE
How is the BoundedParallelIterator supposed to be used?

### ISSUE THREAD

**Issue by WaDelma** [nikomatsakis/rayon#259]
I am currently [experimenting](https://github.com/slide-rs/specs/pull/120) implementing `ParallelIterator` for `specs`.
I have implemented it for the `BitSet` that it uses and and I am now looking at can I implement `BoundedParallelIterator` for it.
I can easily give upper bound how many bits are set in the set, but the trait seems to be designed for randomly indexable collections? Is that oversight or am I missing something?

**Comment by cuviper** [comment]
We're sort of debating its worth in #229.  In theory, we could use the bounds to do something like a sparse `collect`, where we would preallocate for the upper bound, fill in whatever items that we encounter, and the "compress" unused slots after it's done.

But for now, we don't really do anything with this.  I would only bother implementing just `ParallelIterator`, unless you can go all the way to `IndexedParallelIterator`.
