### ISSUE TITLE
Parallel iterators cause huge (~30x) slowdown in Callgrind.

### ISSUE THREAD

**Issue by MortenLohne** [nikomatsakis/rayon#268]
I have a few, small parallel iterators in my program to do very expensive operations in parallel. Everything is fine when I run it standalone, but when I try to profile it in Callgrind, it runs spectacularly slowly, with rayon eating up 97% of my execution time according to the profiling output. When I switch to stdlib iterators, it runs about 30 times faster. I included the callgrind output (Use KCachegrind for human-readable viewing), but the biggest offending functions are: 

- rayon::thread_pool::WorkedThread::steal_work (43%) 
- std::panicking::try::do_call (25%)
- pthread_mutex_lock (11%)
- std::panicking::panicking (10%)

It also only uses one core when running in Callgrind.

I'm not sure if this is normal or to be expected in Callgrind, but I'd really like to able to properly profile this program. I can provide more info if anyone is interested.

[callgrind.out.txt](https://github.com/nikomatsakis/rayon/files/853193/callgrind.out.txt)

**Comment by cuviper** [comment]
Valgrind in general is not great with threading - see here: http://valgrind.org/docs/manual/manual-core.html#manual-core.pthreads

Personally, I use `perf` for profiling rayon.

**Comment by nikomatsakis** [comment]
I'm inclined to close this issue, since it seems like it's not really a rayon problem *per se*. @MortenLohne feel free to re-open or comment if you disagree. Hopefully perf works for you!

**Comment by cuviper** [comment]
FWIW, `valgrind --fair-sched=yes` does seem to do a little better here, but it's still not great.
