### ISSUE TITLE
Allow the user to specify the maximum number of threads that Rayon is allowed to use

### ISSUE THREAD

**Issue by willi-kappler** [nikomatsakis/rayon#28]
Currently Rayon uses all the CPUs / cores available (determined by num_cpus::get()). It would be nice if the user can specify a maximum limit of how many threads Rayon is allowed to use in parallel.

**Comment by lilianmoraru** [comment]
@nikomatsakis Shouldn't this also be closed by #38 ?

**Comment by willi-kappler** [comment]
Yes, thanks for pointing out!
