### ISSUE TITLE
Consider hiding Arc from the Configuration API

### ISSUE THREAD

**Issue by cuviper** [nikomatsakis/rayon#291]
In the `Configuration` setters for panic handler et al., it's awkward that one has to write `Arc::new(||...)` for the closure instead of writing it bare.  We probably should at least drop this part, and `Arc` it internally.  The setters would be generic over the actual closure type.

The getters for these handlers return `Arc` clones.  We could also hide this, and return a reference instead.  It's a little weird to imagine what users would do with these getters at all.  However, `Registry::new` is using that to effectively move them -- get a clone of the `Arc`, then drop the `Configuration`.  And that explains what the comment removed in #290 was thinking, as returning a reference won't work there.

We could make the getters steal the value again, but this can't be generic, so if not `Arc` then it could only be `Box`.  Or if we want these choices to simply be hidden from users, then we could change these getters to free functions in `mod configuration`.

**Comment by nikomatsakis** [comment]
Did this in https://github.com/nikomatsakis/rayon/pull/292
