### ISSUE TITLE
CPU load differences on version 0.7

### ISSUE THREAD

**Issue by 0x7CFE** [nikomatsakis/rayon#296]
My software performs quite intensive computation task (hundreds of thousands of Fourier transforms).

After upgrading to Rayon version 0.7 I noticed that CPU load dropped from ~99% to ~80%.

At first I thought it was a regression but when I performed some measurements I found that the new version does slightly better on the same dataset:

Rayon 0.6 | Rayon 0.7
------------- | --------------
real    2m31.903s | **real    2m17.741s**
user    24m44.952s | **user    20m44.592s**
sys     3m16.764s | **sys     0m7.924s**

Could you please tell me what was changed and why Rayon does not utilize all of my CPU time?

**Comment by cuviper** [comment]
This was briefly mentioned in the release notes:

> Threadpools are now able to more gracefully put threads to sleep when not needed.

Before, if there was *any* active job in the pool, all threads would actively scan for work to steal, without rest.  This is good when things are still getting split up, but it's wasted effort if there's not enough work to go around.  And those scanning threads aren't free, as they add extra traffic on the memory bus, and even compete for local CPU resources on SMT (hyperthreading) machines.

Now in 0.7, individual threads can go to sleep after finding nothing available to steal, so they don't take up any extra processing time.  When new jobs are added anywhere, sleeping threads are awoken to participate again.

There's always a worry of regressions when changing low-level parts like this, so your numbers are **great** to see!  When the same job takes markedly less time, that means we have successfully trimmed wasted work.

Now the task for you, to see if you can do **useful** work on those idle threads, is to look for ways to divide your jobs further.  Maybe you can use the new `with_max_len()` to put an upper bound on the size of each job, forcing it to split up more.  Maybe you can convert some inner part of the computation to split in parallel too.

Remember that more parallelism isn't always a win though, so make sure to keep measuring.  It could be that having more active threads will increase your cache pressure etc. for an actual loss of performance.

**Comment by bluss** [comment]
On numerical workloads I've seen benefits from using one thread per core, discounting hyperthreading. It would be interesting to know how it affects your workload @0x7CFE

**Comment by 0x7CFE** [comment]
@cuviper, thank you very much for such a detailed explanation!

Indeed, after reading release notes all started to be reasonable. Looks like it perfectly describes what is going on in my case.

I have two nested loops where the outer fetches and organizes the input data and the inner loop (`par_iter()` actually) performs the computation and `collects()` the results.

The way I see it, Rayon must preserve the order of values, so there must be some point at the end of each run where Rayon waits for pending workers and collects the data before yielding it to my code. The more such points exist, the more time will be wasted waiting for sync. 

So, in my case I should think how to reogranize the data flow to avoid such stalls.

Ok, now the interesting part. As @bluss mentioned before, in some cases CPUs with hyperthreading may suffer from the load due to cache poisoning. Of course I wanted to know if it happens in my case.

My CPU is
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
Stepping:              2
CPU MHz:               1532.753
CPU max MHz:           4000,0000
CPU min MHz:           1200,0000
BogoMIPS:              7012.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts
```

So I performed runs on various setups and here are the (interesting!) results:

Rayon 0.6 (12 threads) | Rayon 0.7 (12 threads) | Rayon 0.6 (6 threads) | Rayon 0.7 (6 threads)
------------- | -------------- | ---------- | ------------
real    2m31.903s | **real    2m17.741s** | real    2m52.177s | real    3m0.029s
user    24m44.952s | user    20m44.592s | user    16m9.376s | **user    15m41.860s**
sys     3m16.764s | sys     0m7.924s | sys     0m55.732s | **sys**     **0m4.488s**

Looks like the fastest one is **12 thread version running Rayon 0.7**! SMT may be useful, yay!

Interestingly, 6 threaded version of Rayon 0.6 outperforms the Rayon 0.7, but that's probably due to thread parking and migration issues.

I may try to explain the results. In my case all heavy computations are performed on a sliding input data window. Basically, my software fetches a portion of signal data and then performs a ton of overlapping FFTs. So the threads share most of the input data and do not compete for the cache, so no cache poisoning occurs. Looks like it's almost an ideal scenario for SMT, hence the results.

Finally, I would really like to thank all authors of the Rayon library and the Rust language. It's amazing how easy and fast one may achieve such results (not mentioning the safety stuff)! That's the real computer science of the 21st century! :)

**Comment by nikomatsakis** [comment]
@0x7CFE very happy to see that it's working better for you -- I was wondering, though -- would it be possible to develop a benchmark form of your application? Is the code open source? If so, is there some way for me to easily reproduce your measurements? I'd **love** to be able to include it in our set of benchmarks so we can test it when we tweak the scheduler.

**Comment by 0x7CFE** [comment]
@nikomatsakis, I think it is possible to develop a benchmark. Unfortunately, source code is not publicly available at the moment. It will be released at some point in the future, when I finish my research.

But essentially it does very simple thing: it tooks an input WAV file, splits it in chunks and then performs a number of overlapping Fourier transforms, each starting with some offset from the previous one.

Here are the actual routines that do the job:
```rust
type Cplx = ::num_complex::Complex<f32>;
type Samples = Vec<Cplx>;
type Spectrum = Vec<Cplx>;

fn build_spectra(first_chunk: &Samples, second_chunk: &Samples, plan: &dft::Plan<f32>) -> Vec<Spectrum> {
    (0 .. SLICES_PER_FRAME).into_par_iter()
        .map( |slice| {
            // Calculate ranges
            let first_range  = slice * SLICE_OFFSET ..;
            let second_range = .. slice * SLICE_OFFSET;

            // Collect the samples
            let mut samples: Samples = first_chunk[first_range].iter()
                .chain(second_chunk[second_range].iter())
                .cloned()
                .collect();

            // Zero pad to the full frame length
            samples.resize(NUM_POINTS, Cplx::default());

            // Perform the FFT
            dft::transform(&mut samples, plan);

            samples as Spectrum
        })
        .collect()
}

fn process_input(filename: &str) {
    let plan = dft::Plan::new(dft::Operation::Forward, NUM_POINTS);
    let mut reader = hound::WavReader::open(filename).unwrap();

    for (first, second) in reader
        .samples::<i16>()
        .map(|s| Cplx::new(s.unwrap() as f32 / i16::max_value() as f32, 0.0))
        .collect_chunks::<Samples>(NUM_POINTS / 2)
        .map(Arc::new) // Wrap each chunk into Arc for cheap cloning
        .tuple_windows()
    {
        // Stop if there are not enough input samples for a half of a frame
        if first.len() < NUM_POINTS / 2 || second.len() < NUM_POINTS / 2 {
            break;
        }

        // Collect overlapping spectra spanning the whole frame
        let spectra = build_spectra(&first, &second, &plan);

        // Do something useful with the spectra using par_iter() of course!
    }
}
```

Yes, the code is not very optimal but hey, that's just a prototype. The tricky part here is the `collect_chunks()` adaptor which accepts input values and yields a collection of N elements. So `(1 .. ).take(5).collect_chunks::<Vec<_>>(5)` will yield `[1, 2, 3, 4, 5]`. 

By the way, I would be happy to have something in the standard library or itertools that work on any iterator. Currently there are `Itertools::chunks()` but it work only on vectors, AFAIR.

In case of a real data this stuff helps to transform a continious stream of samples into chunks that are then merged and passed to DFT. Don't sure whether it's needed in the benchmark, but oh well.

I think for a benchmark one may simply get (or generate) some input data and then pass it to the DFT which will do the job.

**Comment by nikomatsakis** [comment]
ok, @0x7CFE, thanks :)

**Comment by 0x7CFE** [comment]
@nikomatsakis, just in case, if you haven't written the benchmark yet. After some doubts I [released the sources](https://github.com/0x7CFE/cortex) I was mentioning earlier. 

Current implementation is neither useful nor complete, but it may be used as a hint for a proper benchmark. If you would like to get more information, feel free to ask.
