### ISSUE TITLE
Thread-local-ish folding

### ISSUE THREAD

**Issue by novacrazy** [nikomatsakis/rayon#324]
What would be the best way to create a value that is unique to each thread, run `fold` or similar on the sequence and use that thread-local value for the accumulator in each invocation, and return a vector of the accumulators when done?

So that way I can avoid using mutexes and just merge the accumulators manually in the main thread (or whatever) after the parallel fold has finished.

Consider an image, where I can create empty images for each thread, run the separate drawing routines on each thread and put them in the thread-local image, then merge them together at the end. Overlaying is handled implicitly in my use case, so that's not an issue.

I'm also using this on an existing parallel iterator, so chaining them together would probably be beneficial. Otherwise, I might be able to use `split` to split an iterator with the thread-local images in them, then maybe figure a way to join that iterator with the n-length drawing iterator, but I don't think that would work either.

Perhaps some form of `existing_drawing_iter.zip(image_ref_iter.cycle().into_par_iter())` would work... but I don't think it will send a unique image reference to each thread, even if the number of references matches the threadpool thread count.

As a last resort, I could use a hashmap with a thread-id for the key, and just totally ignore `Send + Sync` requirements.

**Comment by cuviper** [comment]
> What would be the best way to create a value that is unique to each thread, run fold or similar on the sequence and use that thread-local value for the accumulator in each invocation, and return a vector of the accumulators when done?

Rayon has a [`fold`](https://docs.rs/rayon/0.7.0/rayon/iter/trait.ParallelIterator.html#method.fold) pretty much exactly like that!  It's not precisely a per-thread split, but rather a per-job, because we don't know beforehand how jobs will be stolen between threads.  But a given `fold` group will execute completely on one thread.  (unless the closure invokes further threading itself.)

Then you can `reduce()` the folded aggregates, or `collect()` a vector of them, or any of the other parallel iterator methods.  The `fold` result is not an *indexed* iterator though, so you won't be able to `zip` it directly.  TBH I'm not sure I understand what you're trying to do with `zip` though.

I think `split` is also a reasonable way to approach this!  You'll get more control about how the image is divided each time, and in the leaf you'll have the whole "chunk" available to you to work with.

**Comment by novacrazy** [comment]
What is a job in this context? I expect the iterator I'm chaining this onto to produce around 5 million values under a realistic workload, so I hope it is close to the number of threads in the threadpool or allocating that many empty images is impossible.

**Comment by novacrazy** [comment]
Also, I never realized rayon's `fold` didn't return a single value, but another iterator. That was stupid of me.

**Comment by novacrazy** [comment]
Okay, I just tested it on a tiny batch with only about 12 values produced by that iterator, and on my 4-core/4-thread machine it created 12 temporary images. That is no more efficient than map. I need an exact number equal to the thread count, no more.

**Comment by cuviper** [comment]
It won't be divided that finely if your data set is larger.  But we intentionally use an adaptive algorithm to continue splitting as jobs are stolen, as it improves the workload balance, so at a first level we can't promise exactly how many jobs there will be.

However, you can influence this calling [`with_min_len`](https://docs.rs/rayon/0.7.0/rayon/iter/trait.IndexedParallelIterator.html#method.with_min_len) to prevent it from splitting farther than you want, and/or [`with_max_len`](https://docs.rs/rayon/0.7.0/rayon/iter/trait.IndexedParallelIterator.html#method.with_max_len) to make sure it splits enough.  Maybe we should also have some control which says exactly "split this many times", but the idea is generally that you're not supposed to need to worry about this specifically.

Another option, if your source is a slice, is to use the [`ParallelSlice`](https://docs.rs/rayon/0.7.0/rayon/slice/trait.ParallelSlice.html)'s `par_chunks` or `par_chunks_mut` to control the exact size of the data you want to work with.

Or ultimately, you can always drop down to `join` and do it exactly how you want yourself. :)

**Comment by novacrazy** [comment]
Those won't work: `no method named `with_max_len` found for type 'rayon::iter::FilterMap<rayon::slice::Chunks<'_, u32>, ...>'`, plus I'm already using chunks for the underlying data sets.

I'd have to buffer up everything before letting it continue.

**Comment by cuviper** [comment]
It has to be used on the indexed part of your iterator, before the filter.

**Comment by novacrazy** [comment]
I like the adaptive stuff for the tiny data points that go through the chunks and filter map, though, so that would impact the performance of those I'm sure. Although if fewer/smaller splits would improve cache locality for those iterations, then performance might be better, but I don't know enough about rayon's internals to say if it would.

I really can't afford any extra memory allocation than absolutely necessary, or any performance degradation anywhere.

**Comment by novacrazy** [comment]
I think I'm just going to go ahead and thread all this manually, since in Rust that's pretty easy, too. Heh.

**Comment by novacrazy** [comment]
Actually, no, I apologize. Using `with_min_length` set to the data set size divided by the current thread count gives exactly what I need.
