### ISSUE TITLE
More FromParallelIterator impls

### ISSUE THREAD

**Issue by djzin** [nikomatsakis/rayon#328]
One feature of regular iterators that I find very useful is the ability to `collect()` into a `Result` or an `Option` from an iterator of `Result`s or `Option`s. I am unable to translate this code into using rayon's parallel iterators, because those impls are missing. `FromIterator`'s impls look like this:

```rust
impl<A, V> FromIterator<Option<A>> for Option<V> where V: FromIterator<A> {..}
impl<A, E, V> FromIterator<Result<A, E>> for Result<V, E> where V: FromIterator<A> {..}
```

Where the error returned in the `Result` case is the first one if there are any. In rayon's case I guess it could be *any* of the results, the rest getting dropped.

```rust
impl<A, V> FromParallelIterator<Option<A>> for Option<V> where V: FromParallelIterator<A>, A: Send {..}
impl<A, E, V> FromParallelIterator<Result<A, E>> for Result<V, E> where V: FromParallelIterator<A>, A: Send, E: Send {..}
```

Very tricky to work out the panic-safe behaviour on this one I suppose...

**Comment by cuviper** [comment]
See #315  😀

**Comment by djzin** [comment]
Wow that is awesome! Great job, where did you buy your time machine to get this done so quickly ^^
