### ISSUE TITLE
Consider switching to the deque from crossbeam

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#33]
We are currently using the deque from the crates.io `deque` package -- however, @aturon informs me that over long uses that deque can leak memory, since it lacks any form of GC to reclaim nodes. The crossbeam deque is a port to use crossbeam's memory reclamation infrastructure, which should keep memory use in check. We should probably switch; however, it would be interesting to first have some Rayon benchmarks in place.

**Comment by rphmeier** [comment]
The strategy which the `deque` crate uses is to store old buffers in a linked list, doubling in size whenever growth is needed. This ends up converging at `2N` space usage for N elements, so it's not an unbounded memory leak. You could alternatively adopt a strategy (requiring modification of the deque crate) to free the extra buffers when the deque provably has no jobs available. A `pop` operation returning "None" might even be enough proof.

**Comment by aturon** [comment]
Note: the other, probably more important reason that crossbeam's deque may ultimately be worth trying out is that it's soon going to go from all `SeqCst` operations to weaker operations in many cases, which will result in far fewer memory barriers. I'm very curious to see how much a difference that winds up making in practice for a consumer like Rayon. (We're still working out some kinks, though.)

**Comment by nikomatsakis** [comment]
Seems like we won't do this (see conversation on #195).
