### ISSUE TITLE
[doc] Configuration::*_handler() doc doesn't specify what the usize argument to the callback is for

### ISSUE THREAD

**Issue by glandium** [nikomatsakis/rayon#333]
I guess it's a thread id, but it should be spelled out.

**Comment by cuviper** [comment]
Ah, we have that specified in the docs on the `StartHandler` and `ExitHandler` type aliases, but after some refactoring these are no longer public.  Care to send pull request clarifying this?

To be a little more precise, it's the index of the thread in our own pool, not the OS thread id.

**Comment by glandium** [comment]
What can one do in the handler with that index?

**Comment by cuviper** [comment]
You can use it for whatever bookkeeping you like, especially to associate the start and exit of a given thread.
