### ISSUE TITLE
`ParallelIterator::chain` should drive in parallel

### ISSUE THREAD

**Issue by cuviper** [nikomatsakis/rayon#342]
`Chain`'s current `drive` and `drive_unindexed` just split their consumers and then drive each side of the chain separately.  This is not ideal, as we've noted before: https://github.com/nikomatsakis/rayon/issues/112#issuecomment-261996194 and https://github.com/nikomatsakis/rayon/issues/338#issuecomment-301648696

My first instinct was to just `join` the two, but we can't because `ParallelIterator` doesn't require `Send`.  Maybe we could add that, but it means for instance that every `Fn(...) + Sync` closure we accept will also have to add `Send`.  This seems too burdensome, but I don't know how common it is that a `Sync` type would not also be `Send`.  At least for `Fn` in particular, users might get around this by passing their `Sync`-but-not-`Send` closure as `&Fn`.

For `drive`, we could just `bridge` right away, which converts us to a `ChainProducer` that does deal with both parts simultaneously.  That code is a bit complicated though, the way it carries around empty iterators to satisfy types -- feels like it would be preferable to avoid.  It might do better with `Option`s, explicit `None` on split-away sides.

For `drive_unindexed`, I don't have any ideas how to properly parallelize it.

**Comment by nikomatsakis** [comment]
> This seems too burdensome, but I don't know how common it is that a Sync type would not also be Send

I suspect this is not a big problem. It is very rare indeed for a type to be `Sync` and not `Send`; there are theoretical examples, but none that I know of that are in actual use.

You wouldn't, in any case, have to change the *closure* to be a `&F`, but rather just the individual captured variable.
