### ISSUE TITLE
Rayon 0.7.0: unbounded spins in Sleep::no_work_found

### ISSUE THREAD

**Issue by julian-seward1** [nikomatsakis/rayon#343]
Here's the scenario:

Two worker threads, single (timesliced) core, or for whatever reason, the OS is
in a situation where it only runs one of our threads at once

T1 is in sleepy state

T2 is looking for work and iterates through no_work_found.
Its |yields| value rises to ROUNDS_UNTIL_SLEEPY

At this point, it loops:
   calls get_sleepy, which returns false, because T1 is sleepy
   so no_work_found returns |yields| unchanged

No other thread can run, so the global state of the system
remains unchanged, and T2 spins around this loop until the end of
its timeslice.

**Comment by julian-seward1** [comment]
This is easy to demonstrate with the patch shown below, when running a
Stylo-enabled Firefox build with 4 Stylo threads (natively, not on Valgrind,
as has been previously discussed), and is particularly noticable when other
cores are busy with long-running tasks.  There are long sequences of lines
indicating that a thread has become "stuck" at ROUNDS_UNTIL_SLEEPY, in
some cases for hundreds of iterations:

QQQ [23896] no_work_found: wi 1, yields 32
QQQ [23897] no_work_found: wi 1, yields 32
QQQ [23898] no_work_found: wi 1, yields 32
etc

The total number of lines of logging output often exceeds 100000 when
Stylo styles a single page.

diff --git a/third_party/rust/rayon-core-mod/src/sleep/mod.rs b/third_party/rust/rayon-core-mod/src/sleep/mod.rs
--- a/third_party/rust/rayon-core-mod/src/sleep/mod.rs
+++ b/third_party/rust/rayon-core-mod/src/sleep/mod.rs
@@ -14,16 +14,18 @@ pub struct Sleep {
 }
 
 const AWAKE: usize = 0;
 const SLEEPING: usize = 1;
 
 const ROUNDS_UNTIL_SLEEPY: usize = 32;
 const ROUNDS_UNTIL_ASLEEP: usize = 64;
 
+static mut EVENT_CTR: i32 = 0;
+
 impl Sleep {
     pub fn new() -> Sleep {
         Sleep {
             state: AtomicUsize::new(AWAKE),
             data: Mutex::new(()),
             tickle: Condvar::new(),
         }
     }
@@ -42,40 +44,50 @@ impl Sleep {
 
     fn with_sleepy_worker(&self, state: usize, worker_index: usize) -> usize {
         debug_assert!(state == AWAKE || state == SLEEPING);
         ((worker_index + 1) << 1) + state
     }
 
     #[inline]
     pub fn work_found(&self, worker_index: usize, yields: usize) -> usize {
+        unsafe {
+            EVENT_CTR = EVENT_CTR + 1;
+            println!("QQQ [{}]    WORK_FOUND: wi {}, yields {}",
+                     EVENT_CTR, worker_index, yields);
+        }
         log!(FoundWork {
             worker: worker_index,
             yields: yields,
         });
         if yields > ROUNDS_UNTIL_SLEEPY {
             // FIXME tickling here is a bit extreme; mostly we want to "release the lock"
             // from us being sleepy, we don't necessarily need to wake others
             // who are sleeping
             self.tickle(worker_index);
         }
         0
     }
 
     #[inline]
     pub fn no_work_found(&self, worker_index: usize, yields: usize) -> usize {
+        unsafe {
+            EVENT_CTR = EVENT_CTR + 1;
+            println!("QQQ [{}] no_work_found: wi {}, yields {}",
+                     EVENT_CTR, worker_index, yields);
+        }
         log!(DidNotFindWork {
             worker: worker_index,
             yields: yields,
         });
         if yields < ROUNDS_UNTIL_SLEEPY {
             thread::yield_now();
             yields + 1
         } else if yields == ROUNDS_UNTIL_SLEEPY {

**Comment by julian-seward1** [comment]
Adding the "missing" thread::yield_now() call reduces the number of lines
of log output to typically around 10K (a 10-fold reduction) and always
less than 31K in some simple testing:

     #[inline]
     pub fn no_work_found(&self, worker_index: usize, yields: usize) -> usize {
         log!(DidNotFindWork {
             worker: worker_index,
             yields: yields,
         });
         if yields < ROUNDS_UNTIL_SLEEPY {
             thread::yield_now();
             yields + 1
         } else if yields == ROUNDS_UNTIL_SLEEPY {
+            thread::yield_now();
             if self.get_sleepy(worker_index) {
                 yields + 1
             } else {
                 yields
             }
         } else if yields < ROUNDS_UNTIL_ASLEEP {
             thread::yield_now();
             if self.still_sleepy(worker_index) {

**Comment by julian-seward1** [comment]
Talos results are
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=b66103f56d70c5afed2efdcd8748b447c64b4dcf&newProject=try&newRevision=dfb945d3124c58ca74b98a0053a8d3f83ee85d4f&framework=1&showOnlyImportant=0
which looks pretty harmless.

**Comment by nikomatsakis** [comment]
@julian-seward1 

> Adding the "missing" thread::yield_now() call

Indeed, as we discussed earlier, I agree we should be yielding on that path, although it may be that it would be better to **only** yield in the case where we are unable to increment the `yields` counter.

But also, would you be up for opening a PR with this change?

>  which looks pretty harmless.

Can you clarify what you mean by "looks harmless" here? (i.e., the patch does not hurt performance too badly? or the problem doesn't seem too bad in the first place?)

**Comment by cuviper** [comment]
> Indeed, as we discussed earlier, I agree we should be yielding on that path, although it may be that it would be better to only yield in the case where we are unable to increment the yields counter.

FWIW, I also agree that the yield makes more sense on the `else` path.

**Comment by julian-seward1** [comment]
@cuviper

> FWIW, I also agree that the yield makes more sense on the else path.
What is the insight behind that?  My impression is, from profiling Stylo, that
if we get in a state where there is not enough work then it is important to
have idle threads descheduled as soon as possible.

@nikomatsakis

> Can you clarify what you mean by "looks harmless" here?
I meant, it does not show any significant performance change on Talos.

I do think the problem is significant, in that if the machine is busy with other
processes *and* there isn't enough work for the threads, it is possible to observe
spins in practice.

I will do a Talos run for the alternative proposal, yielding only when we can't
increment the counter.

In that situation, in which we would have a purely compute bound spinloop for
63 out of the 64 iterations (involving no system call), has there been consideration
given to putting a "pause" instruction in the loop, to tell the processor we're
doing useless work?
https://software.intel.com/en-us/articles/benefitting-power-and-performance-sleep-loops

**Comment by nox** [comment]
Do we really need more Talos runs? This is absolutely killing us in Servo because we had to tone down Rayon's parallelism on CI. Can we get a fix ASAP? Seems like the patch mentioned in https://github.com/nikomatsakis/rayon/issues/343#issuecomment-303068127 would do the job, no?

**Comment by bholley** [comment]
> Do we really need more Talos runs?

In general, we should absolutely verify the performance characteristics of changes to rayon before landing them. Talos is necessary but not sufficient there, as I've mentioned elsewhere to Julian.

> This is absolutely killing us in Servo because we had to tone down Rayon's parallelism on CI.

Can you elaborate on this, and why you think it's related to this issue? This is the first I've heard of it.

**Comment by emilio** [comment]
> Can you elaborate on this, and why you think it's related to this issue? This is the first I've heard of it.

We had to reduce the number of parallel processes that ran on Servo's CI when upgrading to Rayon 0.7, and this is so far the best hypothesis about why was that necessary.

**Comment by nikomatsakis** [comment]
So here is my take. I think we should make some change here, clearly. But I see a couple of things we could tinker with and I'd love some way to verify what the right changes are:

- We could change the various constants controlling how many times each thread will search for work before going to sleep. They are set rather high right now, I suspect.
- @julian-seward1 raised the possibility in the past that we are invoking `thread::yield` too often; one might consider invoking it **only** in the case where we fail to spin (i.e., right now we invoke it after each failed attempt to find work).
- There is also this `pause` instruction, which I hadn't considered.

**Comment by nikomatsakis** [comment]
(I also really feel like we need some representative benchmarks in rayon-demo, so that we can try to prevent future regressions, but that's not a blocker to making some progress here, of course.)

**Comment by nikomatsakis** [comment]
OK, having pondered this just a bit, I think I am inclined to do this:

- For now, insert an **unconditional** `thread::yield` call in this case where we attempt to transition into sleepy (basically, @julian-seward1's proposed patch)
- Observe the effect on servo's CI, talos
- Tinker with tuning the constants and changing the yield strategy, trying to observe the effects and hopefully derive some test cases we can use in the future to try and predict performance effects.
    - For example, I'd like to make a stylo test case that uses the same branching pattern
    - It'd also be nice to see if we can find a way to measure the effect of many processes running in parallel

The reason I think that the proposed patch makes sense is that it seems consistent with the existing strategy, which basically invokes `thread::yield` after every attempt to search for work. I'm not sure this is the *best* strategy, but it seems like changing the fewest variables at once to follow it.

One challenge I see: It seems there isn't much clarity on what problems servo is having *exactly* -- it's basically more tests timing out or having intermittent failures on CI, from what I understand. This could be some combination of rayon threads hogging up their timeslices (leading to longer test times) combined with existing bugs being exposed. So it's hard to say how we can know if we are "reproducing" those  problems in the small without running the full test harness, I guess.

**Comment by nikomatsakis** [comment]
A thought from IRC: 

We could create a PR for servo that (a) applies the existing patch and (b) increases the number of concurrent processes and then (c) do a `@bors-servo try` run or whatever, and see what happens.

**Comment by julian-seward1** [comment]
> I will do a Talos run for the alternative proposal, yielding only when we can't
> increment the counter.

Let's call the 3 versions "baseline", "all-yield" (my proposal) and "min-yield" (where
we yield only in the case where |yield| is unchanged.  Talos results are:

baseline vs all-yield [1]
baseline vs min-yield [2]

These show no significant speed differences.  There are some weird changes
relating to tp5o_webext XRes opt e10s and tp5o XRes opt e10s.  I have no idea
what they signify.  Note that [1] duplicates the measurements shown further up
(2 days ago) and they show no such changes.

@nikomatsakis 
> OK, having pondered this just a bit, I think I am inclined to do this:

I would prefer to go with this (the all-yield change) too.  Anything else is too large
of an unknown right now.

[1]
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=1d4ed2f611c7903fcfab7dd663b03adcf47ae7f3&newProject=try&newRevision=6cc903510bd6ef1667624d8efb894dc2b2848a71&framework=1&showOnlyImportant=0

[2]
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=1d4ed2f611c7903fcfab7dd663b03adcf47ae7f3&newProject=try&newRevision=cc1f13dc9f31d8b145f624d1805006abc3c13a28&framework=1&showOnlyImportant=0

**Comment by emilio** [comment]
https://github.com/servo/servo/pull/17024

**Comment by nikomatsakis** [comment]
@julian-seward1 and I discussed on IRC. He mentioned wanting to do some further measurements. I also, btw, started [this wiki page](https://github.com/nikomatsakis/rayon/wiki/Benchmarking-Rayon), which should eventually describe procedures for benchmarking rayon changes against stylo and the like.

**Comment by julian-seward1** [comment]
I've tested this (the all-yield change) to, I think, everybody's satisfaction.
How do we move forward with it now?

**Comment by cuviper** [comment]
How about a pull request?

**Comment by julian-seward1** [comment]
@cuviper: done (I think .. git and github are all new to me).  Is there anything
else I need to do?
