### ISSUE TITLE
Join after split when used with rayon::join

### ISSUE THREAD

**Issue by Nokel81** [nikomatsakis/rayon#345]
I hope this is the correct place for this,

In the readme for rayon, the following example is shown:

```rust
fn quick_sort<T:PartialOrd+Send>(v: &mut [T]) {
    if v.len() <= 1 {
        return;
    }

    let mid = partition(v);
    let (lo, hi) = v.split_at_mut(mid);
    rayon::join(|| quick_sort(lo), || quick_sort(hi));
}
```

However, if I wanted to do a merge sort in the same vein, I would be merging the array after the `split_at_mut` but this causes a `cannot assign to `array[..]` because it is borrowed` error. After searching online I cannot find documentation on this problem (which I know is not exactly from rayon) but I think that the readme could benefit with at least an example of dealing with this problem

**Comment by cuviper** [comment]
I think this is probably just a case of wanting non-lexical lifetimes, but you can add a lexical end to the `split_at_mut` borrow by using a block, like:

```rust
    let mid = partition(v);
    {
        let (lo, hi) = v.split_at_mut(mid);
        rayon::join(|| quick_sort(lo), || quick_sort(hi));
    }
    // now `v` is free to be modified again here
```

**Comment by Nokel81** [comment]
Thanks
