### ISSUE TITLE
Call "$CC" not "cc".

### ISSUE THREAD

**Issue by cedenday** [nikomatsakis/rayon#361]

**Comment by cuviper** [comment]
Please provide more details when filing a bug report.  What is your actual problem, and why do you think the issue belongs to this project?  Rayon doesn't explicitly call cc at all.

**Comment by cedenday** [comment]
https://gist.github.com/cedenday/07ed14756e02c1e5b9b6c9996cecc632

Yes it does.

**Comment by cuviper** [comment]
It's still not Rayon -- the `rustc` compiler itself controls its linker [here](https://github.com/rust-lang/rust/blob/03abb1bd70ac56e4aba0684bab819892a0157843/src/librustc_back/target/mod.rs#L417).  You can override that with `-Clinker`, and get Cargo to use that by putting it in `RUSTFLAGS`, e.g. `export RUSTFLAGS="-Clinker=$CC"`.  If you want to ask for `rustc` to automatically use `$CC`, you should file an issue on [rust-lang/rust](https://github.com/rust-lang/rust).

**Comment by cedenday** [comment]
What is this then? https://raw.githubusercontent.com/cedenday/rshare/a79c52c8f00885353decc30439c44367b38b416c/.cargo/config

**Comment by cuviper** [comment]
OK, that's another way to set the linker, but it only takes effect if you choose that target, and your results indicate that your toolchain defaults to `x86_64-unknown-linux-gnu`.  Try `cargo build --release --target x86_64-unknown-linux-musl`.

And still, none of this has anything to do with Rayon.  I'm going to close this issue, and I suggest you ask general Rust questions on the [users forum](https://users.rust-lang.org/).
