### ISSUE TITLE
change from unstable cargo feature to RUSTFLAGS

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#369]
So we encountered some problems that people are relying on things gated by "feature=unstable" (e.g., #364). This isn't really surprising. I was thinking that a better approach would be use a `cfg` flag that is not tied to a feature. Therefore, in order to build Rayon with experimental features, you would have to do:

    RUSTFLAGS='--cfg rayon_unstable' cargo build

This flag will propagate to the rayon create, which will then include unstable features. This has the same "infectious" property that Rust nightly builds do: you can't use an unstable feature in your crate without the top-level crate being forced to acknowledge it.

**Comment by nikomatsakis** [comment]
I implemented this idea idea in #368

**Comment by sanmai-NL** [comment]
@nikomatsakis: I read your issue report and the issue you referred to, but I don’t yet understand what the advantage of using a `cfg` flag is here, over using a Cargo feature. I suppose you implicitly were talking about keeping the `rayon-core` and `rayon` in sync. Before I continue, is that correct?
