### ISSUE TITLE
implement `flatten` from itertools

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#383]
The `itertools` crate offers [a `flatten` method](https://docs.rs/itertools/0.6.0/itertools/trait.Itertools.html#method.flatten). From the docs, "This is more or less equivalent to .flat_map with an identity function."

Implementing this in Rayon should be fairly straightforward, since we support `flat_map`. You basically have to extend [the `ParallelIterator` trait](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/mod.rs#L123) with a new adapter that [invokes `flat_map`](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/mod.rs#L209-L216). Naturally we should include some documentation.

There is however one complication. Lacking `impl Trait`, we can't embed a closure type in the signature. Moreover, implementing the `Fn` trait directly is not possible on stable Rust. This will therefore require creating a custom adapter `Flatten` -- this could be a cut-and-paste job from [`flat_map`](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/flat_map.rs#L10-L13), but that's unappealing. Another option would be to implement the `ParallelIterator` trait for `flatten` and have it invoke `flat_map` during the `drive` function. Something like this:

```rust
impl<I, F, PI> ParallelIterator for Flatten<I>
    where I: ParallelIterator<Item=PI>,
          PI: IntoParallelIterator,
{
    type Item = PI::Item;

    fn drive_unindexed<C>(self, consumer: C) -> C::Result
        where C: UnindexedConsumer<Self::Item>
    {
        self.flat_map(|x| x).drive_unindexed(consumer)
    }
}
```

For a general overview of how the parallel iterator traits work, see [the README](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/README.md).

**Comment by cuviper** [comment]
> Another option would be to implement the ParallelIterator trait for flatten and have it invoke flat_map during the drive function.

That would be my preference.
