### ISSUE TITLE
implement `interleave` and `interleave_shortest` from itertools

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#384]
The `itertools` crate offers [a `interleave` method](https://docs.rs/itertools/0.6.0/itertools/trait.Itertools.html#method.interleave) and `interleave_shortest`. From the docs, "Alternate elements from two iterators until both run out." First task is probably to figure out the *precise* specification here (e.g., by reading the code), since I find that a bit ambiguous, and both methods use the same example, so it's hard to see the difference.

Of the existing adapters, `interleave` most resembles [`zip`](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/zip.rs#L7-L10). I believe this means that, like `zip`, it will require that the two input iterators support `IndexedParallelIterator` (see the [parallel iterator README](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/README.md) for more details).

The basic sketch, like zip, would be to convert both of the input iterators into producers. They can then be split in lockstep. At the point where we convert to sequential execution we can just leverage the `itertools` crate (which is already a dependency of `rayon`).

**Comment by cuviper** [comment]
> They can then be split in lockstep.

Yes, but it's a little tricky -- if the split index is an odd number, then the right side should start with an item from the second iterator.  Another odd split will flip that back, etc.

> we can just leverage the itertools crate (which is already a dependency of rayon).

I don't think it is, but I would be fine with that as long as it's kept internal.
(perhaps you're thinking of `either`, which we added independently.)

**Comment by nikomatsakis** [comment]
>  (perhaps you're thinking of either, which we added independently.)

yeah I was

**Comment by laumann** [comment]
I'd like to give this a go, if no one else is on it...

**Comment by laumann** [comment]
@nikomatsakis @cuviper I'm working on it now - should I add `itertools` as a dependency (it doesn't seem to be there) or should I re-implement it from scratch?

**Comment by cuviper** [comment]
I think the dependency is fine, but you may have a problem that they're not exact or double-ended.

**Comment by laumann** [comment]
I've implemented a `InterleaveSeq` that wraps `itertools::Interleave` and requires DoubleEndedIterator and ExactSizedIterator. I'm currently struggling with this message that I don't quite get:

```
error[E0276]: impl has stricter requirements than trait
    --> src/iter/interleave.rs:55:5
     |
55   |       fn drive<C>(self, consumer: C) -> C::Result
     |  _____^ starting here...
56   | |         where C: UnindexedConsumer<Self::Item>
57   | |     {
58   | |         bridge(self, consumer)
59   | |     }
     | |_____^ ...ending here: impl has extra requirement `C: iter::internal::UnindexedConsumer<<I as iter::ParallelIterator>::Item>`
     | 
    ::: src/iter/mod.rs
     |
1035 |       fn drive<'c, C: Consumer<Self::Item>>(self, consumer: C) -> C::Result;
     |       ---------------------------------------------------------------------- definition of `drive` from trait
```
I have the feeling that I'm missing something really obvious, but I haven't figured it out yet. I've been looking mostly to the implementations of `zip` and `chain` for hints.

Reading the help for `E0276` suggests that I have added an extra requirement for the trait bound that I cannot legally add. (That C's `Item` is also a ParallelIterator?).

Any hints/help is appreciated :-)

**Comment by laumann** [comment]
Oh, think I got it - I was blind. `C` was supposed to be `Consumer`, not `UnindexedConsumer`.

**Comment by laumann** [comment]
OK - I think I have most of the infrastructure in place, and am currently working on `split_at()` which is causing me a bit of trouble.

**Comment by laumann** [comment]
I pushed the code I have so far. I'll probably amend the commit, once I figure out `split_at`. It starts here: [src/iter/interleave.rs:split_at()](https://github.com/laumann/rayon/commit/daa2eeae5c887b859d8014620e2b0cbfd765b65a#diff-22830fe46fb716b3b5969d6dfb7374d0R164)

**Comment by cuviper** [comment]
@laumann You didn't explain your trouble, but  I'll take a guess at the problem... I think your flag needs to be toggled, not just set to `!even`.  That way two odd splits will get it back to the even state.

**Comment by laumann** [comment]
@cuviper Thanks for the tip - I figured I just needed some time to sort it out, but I never got back to it, sorry :-) I'll try to finish it tomorrow!

**Comment by laumann** [comment]
This is half-done with #405 being merged. If https://github.com/nikomatsakis/rayon/wiki/Itertools-Parity is being kept up to date, I think both `interleave` and `zip_eq` can be checked.

I'm working on `interleave_shortest`
