### ISSUE TITLE
doc: Crate missing `html_root_url` attribute

### ISSUE THREAD

**Issue by alexcrichton** [nikomatsakis/rayon#424]
This'll help cross-crate links in foreign crates! It should be set to https://docs.rs/rayon/$version

**Comment by KodrAus** [comment]
Looks like this one's all done @cuviper.

**Comment by cuviper** [comment]
Let's get the same addition for rayon-core and the pending rayon-futures.

**Comment by smt923** [comment]
@cuviper, I'm working on adding the attribute to rayon-core and rayon-futures, should I just match the docs.rs version to whatever is in the Cargo.toml? For both crates, that current version doesn't have published docs, but should I just leave it and assume when a release gets pushed it'll all work?
