### ISSUE TITLE
Scope::spawn doesn't require `Send`

### ISSUE THREAD

**Issue by alexcrichton** [nikomatsakis/rayon#430]
I think it should though!

**Comment by cuviper** [comment]
This is a nasty oversight.  `rayon::spawn` does require `Send`, but we missed this on `Scope::spawn`.  We should probably add `Send` in the private `job` internals, perhaps all the way down to `Job` trait, then the requirement should trickle up to `Scope::spawn`.

It will be a breaking change to rayon-core, but I think justifiable as a soundness fix.

**Comment by nikomatsakis** [comment]
> It will be a breaking change to rayon-core, but I think justifiable as a soundness fix.

Gotta do it.
