### ISSUE TITLE
Windows method

### ISSUE THREAD

**Issue by Michael-F-Bryan** [nikomatsakis/rayon#434]
It'd be nice if there was a `windows()` method on `ParallelIterator` which works similarly to [`[T]::windows()`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.windows).

I've got a use case where I need to apply an operation to consecutive pairs in an array (e.g. for `[a, b, c, d]` I need to operate on `(a, b)`, `(b, c)`, ...). The process itself is trivially parallelizable, so it makes sense to try and use `rayon` to take advantage of the extra cores on a user's machine.

I'm imagining something like this:

```rust
let some_vector = vec![...];

let result: Vec<_> = some_vector.par_iter()
  .windows(|window| {
    let left = &window[0];
    let right = &window[1];
    expensive_calculation(left, right)
  })
  .collect();
```

**Comment by cuviper** [comment]
There is such an extension for slices: try `some_vector`[`.par_windows()`](https://docs.rs/rayon/0.8.2/rayon/slice/trait.ParallelSlice.html#method.par_windows)`.map(...)`.

**Comment by Michael-F-Bryan** [comment]
Oh awesome. I'm going to close this issue then.
