### ISSUE TITLE
Nesting `.install` calls causes deadlock

### ISSUE THREAD

**Issue by torkleyy** [nikomatsakis/rayon#446]
It seems that nesting `.install` calls causes a deadlock at a certain limit. The docs for `ThreadPool::install`, `ThreadPool::scope` and `ThreadPool::join` should be updated to reflect that. Here's my workaround, not sure if it's recommended but it works:

```rust
if pool.current_thread_index().is_none() {
    pool.install(do_something);
} else {
    do_something();
}
```

**Comment by cuviper** [comment]
Thanks for reporting this! We should be able to fix this, at least for a single pool. Separate pools can also block each other though, and I'm not sure there's a good way to fix that.

**Comment by cuviper** [comment]
I'm testing a fix for this.  I'll add it to #443, because they touch similar parts of code.
