### ISSUE TITLE
publish docs

### ISSUE THREAD

**Issue by flying-sheep** [nikomatsakis/rayon#45]
even autogenned APIdocs without additional effort would be nice.

https://nikomatsakis.github.io/rayon would be an obvious place

**Comment by nikomatsakis** [comment]
Now published at `http://nikomatsakis.github.io/rayon/rayon/`, though I will probably remove the extra rayon directory at some point. But of course you can always find the latest link on `crates.io`.

**Comment by flying-sheep** [comment]
great, thank you!

**Comment by lilianmoraru** [comment]
@nikomatsakis Can you please update the README.md to mention the docs?
Google doesn't seem to help find that link.
