### ISSUE TITLE
Par_iter_mut does not seem to be utilizing available (idle) cores?

### ISSUE THREAD

**Issue by polyfractal** [nikomatsakis/rayon#48]
Full disclaimer, this is likely my fault in some way :)

I'm using Rayon master as the dependency, since I wanted some of the 0.3 features.

My code uses `par_iter_mut` to operate on a vector of "Pages" in parallel.  There are 3969 Pages in total, and each page has variable amount of work.  Total runtime is about 60 seconds on my Macbook air, and it appears to be using at least some of my cores (two cores are fairly heavily utilized, the two virtual hyperthreaded cores less so).

However, I tried to run this on my linux "heavy testing" server (hexacore Xeon E5-1650V2, 12 cores if you count hyperthreading) and find that only a single core is used.  Worse, it appears only a single thread is being spawned with the default rayon settings (e.g. no custom Configuration):

```
$ top -H -p 11163

Threads:   2 total,   1 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.0 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  13200303+total,  4213284 used, 12778974+free,    95156 buffers                    
KiB Swap:  4190204 total,        0 used,  4190204 free.  2135916 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                         
11163 tongz      20   0 1442108 1.296g   2640 R 99.8  1.0   0:39.55 bench_grow                                                                                                      
11164 tongz      20   0 1442108 1.296g   2640 S  0.0  1.0   0:00.00 log4rs config r 
```

If I manually specify how many threads should be used, Rayon spawns the full set of threads... but only one thread is actually used:

```rust
rayon::initialize(rayon::Configuration::new().set_num_threads(12));
```
```
$ top -H -p 10495

Threads:  14 total,   1 running,  13 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.0 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  13200303+total,  4212232 used, 12779080+free,    95128 buffers                    
KiB Swap:  4190204 total,        0 used,  4190204 free.  2135916 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                         
10495 tongz      20   0 2253264 1.296g   2680 R 99.7  1.0   0:28.41 bench_grow                                                                                                      
10496 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 log4rs config r                                                                                                 
10497 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10498 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10499 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10500 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10501 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10502 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10503 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10504 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10505 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10506 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10507 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow                                                                                                      
10508 tongz      20   0 2253264 1.296g   2680 S  0.0  1.0   0:00.00 bench_grow  
```

Is it possible the compiler is optimizing away something?  After the processing is done, I'm printing out some values from the computation to make sure the result is used.  And processing still takes ~40s on my server, which makes me think it isn't just optimized away.

I thought the work chunks might be too small, so I tried variously sized work units and it seems to display the same behavior.

I'm not sure what would be helpful to debug.  The [code itself is here](https://github.com/polyfractal/cajal) (and is mostly an unmitigated disaster atm, I haven't had a chance to clean it up). I'm using the `bench_grow` example as a simple test: `cargo run --release --example bench_grow`

The salient code looks like this:

```rust
fn main() {
    rayon::initialize(rayon::Configuration::new().set_num_threads(12));

    let num_pages = 63u32;
    let dimension = num_pages * PAGE_WIDTH;
    let mut cajal = Cajal::new(num_pages, 0.01, &[1,2,3,7]);

    let start = SteadyTime::now();
    cajal.grow();
    let elapsed =  SteadyTime::now() - start;
    let signal = (*cajal.get_cell(10, 10)).get_signal();
    println!("Elapsed time: {:?} (signal: {})", elapsed, signal);
}
```
```rust
fn grow() {
  self.pages.par_iter_mut()
    .for_each(|page| page.grow());;

  // some sequential processing

  self.pages.par_iter_mut()
    .for_each(|page| page.update());
}
```

**Comment by nikomatsakis** [comment]
Try adding a call to `weight_max` in there?  The default -- which I suspect I should change -- is to assume that each task is very cheap. `weight_max` tells is to treat tasks as very expensive, and hence to avoid lumping them together.

**Comment by polyfractal** [comment]
Ahhh, I see.  That did indeed fix it, full usage across all cores.  Dropped from 40s to 5s :)

I assumed that Rayon assumed the opposite: each task was expensive, and so maybe my tasks weren't expensive enough and were finishing quicker than Rayon could schedule them.  I'll read up on the weighting code, perhaps a middle-ground will work better.

Tangentially, would it be possible for each task to set it's own weight?  E.g. each Page knows how much work it needs to compute before it starts computing, and is relatively variable.  It might be nice if each individual task can set it's weight dynamically.  Not sure if that's feasible with Rayon's architecture though.

Thanks for the help (and for Rayon in general)!
