### ISSUE TITLE
Consider switching to jobsteal

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#50]
jobsteal seems to be a nice library. It might make sense to switch the underlying parallel code here to use it, and just concentrate on the higher-level abstractions in Rayon. Got to do more work on those benchmarks. :)

**Comment by bjz** [comment]
For those looking for the library: https://github.com/rphmeier/jobsteal

**Comment by lilianmoraru** [comment]
In the benchmarks I've seen, rayon seems to perform the best

**Comment by nikomatsakis** [comment]
Probably not going to do this.
