### ISSUE TITLE
Periodic crashes with panic propagation

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#58]
I have been seeing travis builds fail unreliably in the negative panic tests. I'll try to pin this down at some point.

cc @Amanieu

**Comment by nikomatsakis** [comment]
Seems like a great use for `rr` btw :)

**Comment by Amanieu** [comment]
Does this happen with or without the `nightly` feature enabled? Or both?

**Comment by nikomatsakis** [comment]
I believe it was with but I am not 100% sure. Haven't tried to reproduce yet
On Feb 20, 2016 07:14, Amanieu <notifications@github.com> wrote:Does this happen with or without the nightly feature enabled? Or both?

**Comment by nikomatsakis** [comment]
@pnkfelix reported similar periodic problems to me running locally --- @pnkfelix, were you using nightly? any features?

**Comment by pnkfelix** [comment]
I'm using the nightly version of `rustc` itself, but the `nightly` feature of `rayon` is not enabled, unless I misunderstand how the Cargo.toml here works. (All I was doing was `cargo build` and `cargo test`, with no extra flags...)

**Comment by Amanieu** [comment]
After a few hours of debugging I finally realized that I forgot to add a guard somewhere... oops
