### ISSUE TITLE
Fix Rayon for nightlies

### ISSUE THREAD

**Issue by nox** [nikomatsakis/rayon#77]
master doesn't work anymore with 2016-05-12 nightly.

**Comment by mbrubeck** [comment]
Fixed in the next nightly by rust-lang/rust#33596?

**Comment by nikomatsakis** [comment]
Ought to be, but I'll release a 0.4.0. (It may be time to release 1.0, actually?)

**Comment by nikomatsakis** [comment]
I just released v0.4.0 in any case, since I think there are some upcoming WF fixes.

**Comment by nox** [comment]
I guess we can close this?
