### ISSUE TITLE
`par_iter` for `Option`

### ISSUE THREAD

**Issue by hauleth** [nikomatsakis/rayon#80]
It would be nice to have one to allow uses like:

```rust
paths
    .map(File::open)
    .flat_map(Result::ok)
    // ...
```

**Comment by cuviper** [comment]
Doesn't `filter_map` work for this?

**Comment by hauleth** [comment]
It is, I didn't know that this existed, but still, this should be easy to implement such and then allow parallelization of iteration with just `s/iter/par_iter`.

**Comment by cuviper** [comment]
I suspect `flat_map` with `Option` will perform worse than a direct `filter_map`, for both normal and parallel iterators, but yes it should be easy to implement.
