### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by edre** [nikomatsakis/rayon#82]
There is no indication how or whether rayon is open source.

**Comment by nikomatsakis** [comment]
Hmm. The intention is to use the standard Apache2/MIT combo that Rust uses.

**Comment by aij** [comment]
There is this...

https://github.com/nikomatsakis/rayon/blob/3a10365d9f134a35af463f700b244d48c253132d/Cargo.toml#L6

It would appear to be an indication that the license is Apache-2.0/MIT.

**Comment by edre** [comment]
For clarity, can you copy over the license file[s] that rust uses?

**Comment by nikomatsakis** [comment]
That would be fine, yes. I'll do it soon, but PRs welcome too =)
