### ISSUE TITLE
v0.4.0 is out but not in RELEASES

### ISSUE THREAD

**Issue by Eh2406** [nikomatsakis/rayon#84]
Hi:

https://crates.io/crates/rayon clames `rayon = "0.4.0"` but RELEASES.md clames Release 0.4 (not yet released)

What is new in 0.4.0?

**Comment by cuviper** [comment]
The `release-v0.4.1` branch has an [updated `RELEASES.md`](https://github.com/nikomatsakis/rayon/blob/release-v0.4.1/RELEASES.md).
@nikomatsakis Any reason this didn't go on master?

**Comment by cuviper** [comment]
Ah, because it was in PR #99, now merged.  @Eh2406, are you satisfied?

**Comment by Eh2406** [comment]
Yes. Just to be clear, I was not "unsatisfied" I just found an inconsistency and though it may help to point it out. Thank you for fixing it.

**Comment by cuviper** [comment]
Sure, I just meant that loosely, like "are you happy with this?"  And you are, so we're good. :)
