### ISSUE TITLE
impl par_iter for other std collections.

### ISSUE THREAD

**Issue by Aaronepower** [nikomatsakis/rayon#88]
Currently if you want parallelize iterating through anything that can't easily be turned into a `Vec<T>` or `&[T]` you have perform a `collect`, which can be quite slow on large collections.

**Comment by cuviper** [comment]
Vectors and slices work because they can be directly partitioned.
How would you do this for other collection types?

**Comment by nikomatsakis** [comment]
So, some thoughts:

First, we could naturally handle hashmaps and other collections by creating (temporary) vectors and parallelizing over those. It'd add overhead but probably not *that* much, and we could I think do it relatively transparently.

I've also been wanting to explore bridges to/from normal sequential iterators for a while. It should be possible to handle them, even if they don't create fully balanced task trees (and hence don't necessarily scale quite as well). That was I think part of the motivation for https://github.com/nikomatsakis/rayon/pull/71; though the precise requirements are a bit out of tree for me just now.
