### ISSUE TITLE
settle on one reduce, one fold

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rayon#94]
Currently we have a lot of method for doing "fold-like" things:

``` rust
    fn reduce_with<OP>(self, op: OP) -> Option<Self::Item>
        where OP: Fn(Self::Item, Self::Item) -> Self::Item + Sync;
    fn reduce_with_identity<OP>(self, identity: Self::Item, op: OP) -> Self::Item
        where OP: Fn(Self::Item, Self::Item) -> Self::Item + Sync,
              Self::Item: Clone + Sync;
    fn reduce<REDUCE_OP>(self, reduce_op: &REDUCE_OP) -> Self::Item
        where REDUCE_OP: ReduceOp<Self::Item>;
```

And of course there is also the (experimental, but faster in some cases) `fold` operation:

``` rust
    fn fold<I,FOLD_OP,REDUCE_OP>(self,
                                 identity: I,
                                 fold_op: FOLD_OP,
                                 reduce_op: REDUCE_OP)
                                 -> I
        where FOLD_OP: Fn(I, Self::Item) -> I + Sync,
              REDUCE_OP: Fn(I, I) -> I + Sync,
              I: Clone + Sync + Send;
```

Part of the challenge here is that parallel reduce is different from fold: you can't just start from the left and combine elements until the end. Instead, you wind up dividing the list into a kind of tree, folding each of those segments from left-to-right, and then reducing the results as you walk up the tree. 

Each of the variations we currently have makes sense in its own way:
- `reduce_with` is simplest, but it's the most inefficient. Because it requires two values from the iterator before we can invoke the closure, it has to introduce options under the hood to track things. Maybe there is a nicer way to implement it?
- `reduce_with_identity` avoids the problem of introducing `Option` by requiring an initial element to use as the "accumulator" value. However, unlike in sequential fold, this value must be _cloneable_, which is unfortunate sometimes. (It has to be cloneable because we will need to use it for each of the parallel segments we wind up with.)
- The original `reduce` was intended for letting people write custom operations that configure each detail. Its pretty silly for this to have the best name, but it might make sense to keep it around.
- The `fold` operation exposes this "tree-and-then-walk-back-up" structure directly. I added it to try and make a benchmark faster. It worked, but it's again somewhat complicated. I think I've decided that it _does_ make sense to keep it around, but I'm not 100% sure. 

My feeling is that we should probably have a variation on `reduce_with_identity` as the **only reduce** operation. It would instead have a closure that produces the identity, so that `sum` looks like this:

``` rust
iterator.reduce(|| 0, |a, b| a+b)
```

At that point, there is no need for the current `reduce`, since the `Reduce` trait just provides two methods that are basically equivalent to these two closures. Moreover, we can lift the `Clone` bounds.

If you need to artifically inject an identity value, as the current `reduce_with` does, it can be expressed like so:

``` rust
iterator.reduce_with(|| None, |a, b| match (a, b) {
    (Some(a), Some(b)) => a+b,
    (s @ Some(_), None) | (None, s @ Some(_)) => s,
    (None, None) => None,
})
```

But I think nobody ever will.

So that just leaves the question of whether to keep `fold` around. My feeling now is that we should, but modify it to take a closure. I can easily imagine cases where it's useful to be able to retain state across the sequential folds, which `fold` makes possible. `fold` also basically corresponds to the `map-reduce` problem -- you can express this as `.map().reduce()` but sometimes it more efficient to convert N items into the new type than to convert each item individually, which is basically the point.

As an example, the nbody demo uses fold like this:

``` rust
iterator.fold(
    || (0, 0), // represents the total "difference" in current position of this item
    |(diff1, diff2), item| ..., // adjust diff1, diff2 based on item
    |(diff1, diff2), (diff1b, diff2b)| (diff1 + diff1b, diff2 + diff2b));
```

Sound good?

cc @jorendorff, @cuviper  -- with whom I talked about this

**Comment by nikomatsakis** [comment]
Just had a random thought about `fold`. It is unfortunate to take 3 closures. I wonder if it would be possible to have an operation that has this signature:

    Fn() -> U
    Fn(U, T) -> U

and basically transforms an iterator over T into an iterator over U. This is then the first part of fold -- it's sort of like a "partial reduce" that randomly picks chunks of your iterator to fold up, so if you have an iterator over T, you wind up with an iterator over some number of U's, but you don't know how many. You can then combine with a reduce to finish everything.

Hence nbody would become:

    iterator
        .fold(
            || (0, 0)
            |(diff1, diff2), item| ...)
        .reduce(|(diff1, diff2), (diff1b, diff2b)| ...)

**Comment by cuviper** [comment]
I like how that fold-reduce looks, but will that interim object be a full `ParallelIterator` itself?

```rust
iterator
  .filter(|&x| x > 0)
  .fold(Vec::new, |v, x| { v.push(x); v })
  .filter(|v| v.len() > 42)
  .flat_map(|v| v)
  .sum()
```

That's contrived nonsense, of course, but perhaps there's some real use to true generality.  And it may be a little confusing if this `FoldIter::reduce` is different than `ParallelIterator::reduce`.

**Comment by cuviper** [comment]
The general point about having one `reduce` to rule them all is great, but I really wish it could be the single-closure form like `reduce_with`.  I don't know how you'd implement this without `Option` though.  It might look more like `Iterator`'s internal `select_fold1`, but that doesn't fit the force-fed `Consumer` model.

*(tangent)* I've also been thinking about short-circuiting ops like `find`, `any`, etc., and these also don't fit well in the current `Consumer` model.  Maybe there's a better push-pull balance we could find here.

**Comment by nikomatsakis** [comment]
@cuviper I have assumed that short-circuiting ops would use a shared `Arc<AtomicBool>` to signal when they should stop (and it'd be somewhat undefined which one you get, of course). 

(But I've also wondered if we ought to make `find` guarantee that you get the first one -- I guess that kind of stinks though.)

**Comment by nikomatsakis** [comment]
I tend to think it's ok for it to take two closures. After all, fold takes two arguments. 

I can't decide whether it's ok to use method names like `fold` (or `find`) which overlap seq iters but give them slightly different semantics (e.g., fold doesn't go L->R).

**Comment by nikomatsakis** [comment]
@cuviper 

> I like how that fold-reduce looks, but will that interim object be a full ParallelIterator itself?

I figured it would be, yes, but I haven't tried to implement it or anything.

**Comment by cuviper** [comment]
> I tend to think it's ok for it to take two closures. After all, fold takes two arguments. 

Yeah, but `fold` has to create the base item at some point, whereas `reduce` could just use the first item it encounters.  Two-closure `reduce` also means you have to repeat yourself:

```rust
iterator
    .fold(
        || (0, 0),
        |(diff1, diff2), item| ...)
    .reduce(
        || (0, 0),
        |(diff1, diff2), (diff1b, diff2b)| ...)
```

**Comment by nikomatsakis** [comment]
@cuviper 

> Two-closure reduce also means you have to repeat yourself...whereas reduce could just use the first item it encounters

Well, if you used one-closure reduce, you would get back an option, so you'd probably wind up writing:

```rust
iterator
    .fold(
        || (0, 0),
        |(diff1, diff2), item| ...)
    .reduce(
        |(diff1, diff2), (diff1b, diff2b)| ...)
    .unwrap_or((0, 0));
``` 

I think the repeating is due to separating `fold` out into a distinct operation. It doesn't really bother me much though.

**Comment by nikomatsakis** [comment]
I implemented the proposed `reduce` method in [this branch](https://github.com/nikomatsakis/rayon/tree/reduce-and-fold). 

I'll try some experiments around `fold`. I'm not even sure if what I proposed can really be implemented nicely.

**Comment by nikomatsakis** [comment]
OK, I've implemented my proposed `fold` too. I'm quite a fan of it, I have to admit. =)

The performance seems to be *ever so slightly* slower than the old `fold`, but basically the same:

```
lunch-box. cargo bench -- nbody
running 4 tests
test nbody::bench::nbody_par                ... bench:  13,558,854 ns/iter (+/- 5,578,199)
test nbody::bench::nbody_parreduce          ... bench:  21,083,144 ns/iter (+/- 9,391,178)
test nbody::bench::nbody_parreduce_master   ... bench:  20,730,507 ns/iter (+/- 10,288,526)
test nbody::bench::nbody_seq                ... bench: 135,046,865 ns/iter (+/- 39,235,146)
```

Here `nbody_parreduce` is the new fold and `nbody_parreduce_master` is the old one. You can see there is a 1.7% difference. I suspect this could be recovered with a bit of tuning and/or rustc optimization, and anyway the new version is certainly more flexible (e.g., you could collect those results into a vector, not just reduce them).
